/**
 * build:maps — convert the XP router's map packs into Solodex map packs.
 *
 *   npm run build:maps                                  # every game
 *   npm run build:maps -- --games=yellow,platinum       # some packs
 *   npm run build:maps -- --router=A:/pkmn_yellow_xp_router --out=resources/maps
 *
 * Reads `<router>/map_data/<pack>/` (generated by pokemap's
 * pipeline/export-router.js) and `<router>/raw_pkmn_data/` (to match trainers),
 * writes `<out>/<pack>.zip` (see src/shared/mapPack.ts for the contents) and
 * docs/maps/coverage.md. Run with vite-node so the renderer's data layer
 * resolves (trainers, species names).
 */
import fs from 'fs'
import path from 'path'
import { getAllPokemon } from '@/data'
import { MAP_PACK_IDS, MAP_PACK_VERSION, type MapPackJson } from '../../src/shared/mapPack'
import { buildCommon } from './common'
import { buildFormat1 } from './format1'
import { buildFormat2 } from './format2'
import { SpriteFrames } from './sprites'
import { trainerResolver } from './trainers'
import { ZipWriter } from './zipWriter'

const ROOT = path.resolve(__dirname, '../..')
const args = process.argv.slice(2)
const opt = (n: string) => args.find(a => a.startsWith(`--${n}=`))?.split('=').slice(1).join('=')
const ROUTER = path.resolve(opt('router') ?? process.env.SOLODEX_ROUTER_DIR ?? 'A:/pkmn_yellow_xp_router')
const OUT = path.resolve(ROOT, opt('out') ?? 'resources/maps')
const ONLY = opt('games')?.split(',').map(s => s.trim()).filter(Boolean)

const canonical = (s: string) => s.toLowerCase().replace(/♀/g, 'f').replace(/♂/g, 'm').replace(/[^a-z0-9]/g, '')

function speciesNormalizer(): (name: string) => string {
  const byCanonical = new Map<string, string>()
  for (const p of getAllPokemon()) byCanonical.set(canonical(p.name), p.name)
  return name => byCanonical.get(canonical(name)) ?? ''
}

interface Report {
  pack: string
  game: string
  bytes: number
  files: number
  stats: Record<string, number>
  unmatchedTrainers: string[]
  nameMismatches: string[]
  unknownSpecies: string[]
  unanchoredTrainers: string[]
}

async function buildPack(packId: string, game: string, species: (n: string) => string): Promise<Report> {
  const dir = path.join(ROUTER, 'map_data', packId)
  const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'))
  const gen: number = manifest.gen
  const tmp = path.join(OUT, `${packId}.zip.tmp`)
  const zip = new ZipWriter(tmp)
  const t0 = Date.now()
  try {
    const rawMaps: Record<string, unknown>[] = JSON.parse(fs.readFileSync(path.join(dir, 'maps.json'), 'utf8'))
    const keyToId = new Map(rawMaps.map((r, i) => [r.const as string, i]))
    const trainers = await trainerResolver(ROUTER, packId, game, gen)
    let base
    let lift: Buffer | null = null
    let labels: { methodLabels?: Record<string, string>; conditionLabels?: Record<string, string> } = {}
    let palettes: unknown = null
    let tod: ((k: string) => string | undefined) | undefined
    if (manifest.format === 1) {
      const envOf = new Map(rawMaps.map(r => [r.const as string, (r.env as string) ?? '']))
      const f1 = await buildFormat1(dir, zip, envOf)
      base = { maps: f1.maps, surfaces: f1.surfaces, world: f1.world, ownership: null, terrain: f1.terrain }
      palettes = f1.pack.palettes
      if (gen === 2) {
        const todOf = new Map(f1.pack.maps.map(m => [m.key, m.palette?.tod]))
        tod = k => todOf.get(k)
      }
    } else if (manifest.format === 2) {
      const f2 = await buildFormat2(dir, zip)
      base = { maps: f2.maps, surfaces: f2.surfaces, world: f2.world, ownership: f2.ownership, terrain: f2.terrain }
      lift = f2.lift
      labels = { methodLabels: f2.methodLabels, conditionLabels: f2.conditionLabels }
    } else {
      throw new Error(`${packId}: unsupported pack format ${manifest.format}`)
    }
    const frames = new SpriteFrames(zip, gen, dir, palettes)
    const common = await buildCommon({ dir, gen, keyToId, tod, frames, trainers, species, ...labels })

    const pack: MapPackJson = {
      version: MAP_PACK_VERSION,
      id: packId,
      gen,
      versions: manifest.versions,
      tilted: manifest.format === 2,
      world: base.world,
      surfaces: base.surfaces,
      ownership: base.ownership,
      maps: base.maps,
      objects: common.objects,
      sprites: frames.sprites,
      encounters: common.encounters,
      methods: common.methods,
      conditions: common.conditions,
      trainers: common.trainers,
      stats: common.stats,
    }
    zip.add('terrain.bin', base.terrain, { deflate: true })
    if (lift) zip.add('lift.bin', lift, { deflate: true })
    zip.add('pack.json', Buffer.from(JSON.stringify(pack)), { deflate: true })
    zip.close()
    fs.renameSync(tmp, path.join(OUT, `${packId}.zip`))

    const { getTrainers } = await import('@/data')
    const unanchored = getTrainers(game).filter(t => !pack.trainers[t.id]).map(t => `${t.id} (${t.name})`)
    console.log(`  ${packId}: ${(zip.bytes / 1e6).toFixed(1)} MB, ${zip.count} files, ${common.objects.length} objects, ` +
      `${Object.keys(pack.trainers).length}/${getTrainers(game).length} trainers placed, ${((Date.now() - t0) / 1000).toFixed(1)} s`)
    return {
      pack: packId,
      game,
      bytes: zip.bytes,
      files: zip.count,
      stats: { ...common.stats, solodexTrainers: getTrainers(game).length },
      unmatchedTrainers: [...common.unmatchedTrainers].sort(),
      nameMismatches: trainers.nameMismatches,
      unknownSpecies: [...common.unknownSpecies].sort(),
      unanchoredTrainers: unanchored,
    }
  } catch (err) {
    try { zip.close() } catch { /* already closed */ }
    fs.rmSync(tmp, { force: true })
    throw err
  }
}

function writeCoverage(reports: Report[]): void {
  const lines = [
    '# Map pack coverage',
    '',
    'Generated by `npm run build:maps`; do not edit. "Placed" trainers have a',
    'position on the map (the Trainers tab\'s Show on map works for them).',
    '',
    '| Pack | Game | Size | Trainers placed | Unmatched router names | Unknown species |',
    '| --- | --- | --- | --- | --- | --- |',
    ...reports.map(r => `| ${r.pack} | ${r.game} | ${(r.bytes / 1e6).toFixed(1)} MB | ${r.stats.trainersAnchored} / ${r.stats.solodexTrainers} | ${r.unmatchedTrainers.length} | ${r.unknownSpecies.length} |`),
    '',
  ]
  for (const r of reports) {
    const sections: [string, string[]][] = [
      ['Router trainer names with no Solodex trainer', r.unmatchedTrainers],
      ['Matches whose names differ (matched by ROM id or position)', r.nameMismatches],
      ['Solodex trainers with no map position', r.unanchoredTrainers],
      ['Encounter species not in the Solodex species index', r.unknownSpecies],
    ]
    if (sections.every(([, l]) => l.length === 0)) continue
    lines.push(`## ${r.game}`, '')
    for (const [title, list] of sections) {
      if (!list.length) continue
      lines.push(`<details><summary>${title} (${list.length})</summary>`, '', ...list.map(s => `- ${s}`), '', '</details>', '')
    }
  }
  fs.mkdirSync(path.join(ROOT, 'docs/maps'), { recursive: true })
  fs.writeFileSync(path.join(ROOT, 'docs/maps/coverage.md'), lines.join('\n'))
}

async function main(): Promise<void> {
  if (!fs.existsSync(path.join(ROUTER, 'map_data'))) {
    console.error(`No map_data in ${ROUTER}. Pass --router=<path to pkmn_yellow_xp_router> or set SOLODEX_ROUTER_DIR.`)
    process.exit(1)
  }
  fs.mkdirSync(OUT, { recursive: true })
  const species = speciesNormalizer()
  const reports: Report[] = []
  for (const [game, packId] of Object.entries(MAP_PACK_IDS)) {
    if (ONLY && !ONLY.includes(packId)) continue
    if (!fs.existsSync(path.join(ROUTER, 'map_data', packId, 'manifest.json'))) {
      console.warn(`  ${packId}: no pack in ${ROUTER}/map_data, skipped`)
      continue
    }
    reports.push(await buildPack(packId, game, species))
  }
  if (!ONLY) writeCoverage(reports)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
