export const tmhm = {
    "1": {
        "TM01": "Mega Punch",
        "TM02": "Razor Wind",
        "TM03": "Swords Dance",
        "TM04": "Whirlwind",
        "TM05": "Mega Kick",
        "TM06": "Toxic",
        "TM07": "Horn Drill",
        "TM08": "Body Slam",
        "TM09": "Take Down",
        "TM10": "Double-Edge",
        "TM11": "BubbleBeam",
        "TM12": "Water Gun",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Pay Day",
        "TM17": "Submission",
        "TM18": "Counter",
        "TM19": "Seismic Toss",
        "TM20": "Rage",
        "TM21": "Mega Drain",
        "TM22": "SolarBeam",
        "TM23": "Dragon Rage",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Fissure",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Teleport",
        "TM31": "Mimic",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Bide",
        "TM35": "Metronome",
        "TM36": "Selfdestruct",
        "TM37": "Egg Bomb",
        "TM38": "Fire Blast",
        "TM39": "Swift",
        "TM40": "Skull Bash",
        "TM41": "Softboiled",
        "TM42": "Dream Eater",
        "TM43": "Sky Attack",
        "TM44": "Rest",
        "TM45": "Thunder Wave",
        "TM46": "Psywave",
        "TM47": "Explosion",
        "TM48": "Rock Slide",
        "TM49": "Tri Attack",
        "TM50": "Substitute",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Flash",
    },
    "2": {
        "TM01": "DynamicPunch",
        "TM02": "Headbutt",
        "TM03": "Curse",
        "TM04": "Rollout",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Zap Cannon",
        "TM08": "Rock Smash",
        "TM09": "Psych Up",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Sweet Scent",
        "TM13": "Snore",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Icy Wind",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Endure",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Iron Tail",
        "TM24": "DragonBreath",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Mud-Slap",
        "TM32": "Double Team",
        "TM33": "Ice Punch",
        "TM34": "Swagger",
        "TM35": "Sleep Talk",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Swift",
        "TM40": "Defense Curl",
        "TM41": "ThunderPunch",
        "TM42": "Dream Eater",
        "TM43": "Detect",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Fire Punch",
        "TM49": "Fury Cutter",
        "TM50": "Nightmare",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Flash",
        "HM06": "Whirlpool",
        "HM07": "Waterfall",
    },
    "3": {
        "TM01": "Focus Punch",
        "TM02": "Dragon Claw",
        "TM03": "Water Pulse",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Bullet Seed",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Iron Tail",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Shock Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Secret Power",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Skill Swap",
        "TM49": "Snatch",
        "TM50": "Overheat",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Flash",
        "HM06": "Rock Smash",
        "HM07": "Waterfall",
        "HM08": "Dive",
    },
    "4": {
        "TM01": "Focus Punch",
        "TM02": "Dragon Claw",
        "TM03": "Water Pulse",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Bullet Seed",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Iron Tail",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Shock Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Secret Power",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Skill Swap",
        "TM49": "Snatch",
        "TM50": "Overheat",
        "TM51": "Roost",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Brine",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Endure",
        "TM59": "Dragon Pulse",
        "TM60": "Drain Punch",
        "TM61": "Will-O-Wisp",
        "TM62": "Silver Wind",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Recycle",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Avalanche",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Stealth Rock",
        "TM77": "Psych Up",
        "TM78": "Captivate",
        "TM79": "Dark Pulse",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Sleep Talk",
        "TM83": "Natural Gift",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Pluck",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Defog",
        "HM06": "Rock Smash",
        "HM07": "Waterfall",
        "HM08": "Rock Climb",
    },
    "5": {
        "TM01": "Hone Claws",
        "TM02": "Dragon Claw",
        "TM03": "Psyshock",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Venoshock",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Telekinesis",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Smack Down",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Sludge Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Flame Charge",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Low Sweep",
        "TM48": "Round",
        "TM49": "Echoed Voice",
        "TM50": "Overheat",
        "TM51": "Ally Switch",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Scald",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Sky Drop",
        "TM59": "Incinerate",
        "TM60": "Quash",
        "TM61": "Will-O-Wisp",
        "TM62": "Acrobatics",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Retaliate",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Volt Switch",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Struggle Bug",
        "TM77": "Psych Up",
        "TM78": "Bulldoze",
        "TM79": "Frost Breath",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Dragon Tail",
        "TM83": "Work Up",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Pluck",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "TM93": "Wild Charge",
        "TM94": "Rock Smash",
        "TM95": "Snarl",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Waterfall",
        "HM06": "Dive",
    },
}