export const tmhm = {
    "1": {
        "TM01": "Mega Punch",
        "TM02": "Razor Wind",
        "TM03": "Swords Dance",
        "TM04": "Whirlwind",
        "TM05": "Mega Kick",
        "TM06": "Toxic",
        "TM07": "Horn Drill",
        "TM08": "Body Slam",
        "TM09": "Take Down",
        "TM10": "Double-Edge",
        "TM11": "BubbleBeam",
        "TM12": "Water Gun",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Pay Day",
        "TM17": "Submission",
        "TM18": "Counter",
        "TM19": "Seismic Toss",
        "TM20": "Rage",
        "TM21": "Mega Drain",
        "TM22": "SolarBeam",
        "TM23": "Dragon Rage",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Fissure",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Teleport",
        "TM31": "Mimic",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Bide",
        "TM35": "Metronome",
        "TM36": "Selfdestruct",
        "TM37": "Egg Bomb",
        "TM38": "Fire Blast",
        "TM39": "Swift",
        "TM40": "Skull Bash",
        "TM41": "Softboiled",
        "TM42": "Dream Eater",
        "TM43": "Sky Attack",
        "TM44": "Rest",
        "TM45": "Thunder Wave",
        "TM46": "Psywave",
        "TM47": "Explosion",
        "TM48": "Rock Slide",
        "TM49": "Tri Attack",
        "TM50": "Substitute",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Flash",
    },
    "2": {
        "TM01": "DynamicPunch",
        "TM02": "Headbutt",
        "TM03": "Curse",
        "TM04": "Rollout",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Zap Cannon",
        "TM08": "Rock Smash",
        "TM09": "Psych Up",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Sweet Scent",
        "TM13": "Snore",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Icy Wind",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Endure",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Iron Tail",
        "TM24": "DragonBreath",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Mud-Slap",
        "TM32": "Double Team",
        "TM33": "Ice Punch",
        "TM34": "Swagger",
        "TM35": "Sleep Talk",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Swift",
        "TM40": "Defense Curl",
        "TM41": "ThunderPunch",
        "TM42": "Dream Eater",
        "TM43": "Detect",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Fire Punch",
        "TM49": "Fury Cutter",
        "TM50": "Nightmare",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Flash",
        "HM06": "Whirlpool",
        "HM07": "Waterfall",
    },
    "3": {
        "TM01": "Focus Punch",
        "TM02": "Dragon Claw",
        "TM03": "Water Pulse",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Bullet Seed",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Iron Tail",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Shock Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Secret Power",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Skill Swap",
        "TM49": "Snatch",
        "TM50": "Overheat",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Flash",
        "HM06": "Rock Smash",
        "HM07": "Waterfall",
        "HM08": "Dive",
    },
    "4": {
        "TM01": "Focus Punch",
        "TM02": "Dragon Claw",
        "TM03": "Water Pulse",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Bullet Seed",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Iron Tail",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Shock Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Secret Power",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Skill Swap",
        "TM49": "Snatch",
        "TM50": "Overheat",
        "TM51": "Roost",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Brine",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Endure",
        "TM59": "Dragon Pulse",
        "TM60": "Drain Punch",
        "TM61": "Will-O-Wisp",
        "TM62": "Silver Wind",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Recycle",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Avalanche",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Stealth Rock",
        "TM77": "Psych Up",
        "TM78": "Captivate",
        "TM79": "Dark Pulse",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Sleep Talk",
        "TM83": "Natural Gift",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Pluck",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Defog",
        "HM06": "Rock Smash",
        "HM07": "Waterfall",
        "HM08": "Rock Climb",
    },
    "5": {
        "TM01": "Hone Claws",
        "TM02": "Dragon Claw",
        "TM03": "Psyshock",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Venoshock",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Telekinesis",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "SolarBeam",
        "TM23": "Smack Down",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Sludge Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Flame Charge",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Low Sweep",
        "TM48": "Round",
        "TM49": "Echoed Voice",
        "TM50": "Overheat",
        "TM51": "Ally Switch",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Scald",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Sky Drop",
        "TM59": "Incinerate",
        "TM60": "Quash",
        "TM61": "Will-O-Wisp",
        "TM62": "Acrobatics",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Retaliate",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Volt Switch",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Struggle Bug",
        "TM77": "Psych Up",
        "TM78": "Bulldoze",
        "TM79": "Frost Breath",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Dragon Tail",
        "TM83": "Work Up",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Pluck",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "TM93": "Wild Charge",
        "TM94": "Rock Smash",
        "TM95": "Snarl",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Waterfall",
        "HM06": "Dive",
    },
    "6xy": {
        "TM01": "Hone Claws",
        "TM02": "Dragon Claw",
        "TM03": "Psyshock",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Venoshock",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Roost",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "Solar Beam",
        "TM23": "Smack Down",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Sludge Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Flame Charge",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Low Sweep",
        "TM48": "Round",
        "TM49": "Echoed Voice",
        "TM50": "Overheat",
        "TM51": "Steel Wing",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Scald",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Sky Drop",
        "TM59": "Incinerate",
        "TM60": "Quash",
        "TM61": "Will-O-Wisp",
        "TM62": "Acrobatics",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Retaliate",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Volt Switch",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Struggle Bug",
        "TM77": "Psych Up",
        "TM78": "Bulldoze",
        "TM79": "Frost Breath",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Dragon Tail",
        "TM83": "Infestation",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Sleep Talk",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "TM93": "Wild Charge",
        "TM94": "Rock Smash",
        "TM95": "Snarl",
        "TM96": "Nature Power",
        "TM97": "Dark Pulse",
        "TM98": "Power-Up Punch",
        "TM99": "Dazzling Gleam",
        "TM100": "Confide",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Waterfall",
    },
    "6": {
        "TM01": "Hone Claws",
        "TM02": "Dragon Claw",
        "TM03": "Psyshock",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Venoshock",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Roost",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "Solar Beam",
        "TM23": "Smack Down",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Sludge Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Flame Charge",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Low Sweep",
        "TM48": "Round",
        "TM49": "Echoed Voice",
        "TM50": "Overheat",
        "TM51": "Steel Wing",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Scald",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Sky Drop",
        "TM59": "Incinerate",
        "TM60": "Quash",
        "TM61": "Will-O-Wisp",
        "TM62": "Acrobatics",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Retaliate",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Volt Switch",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Struggle Bug",
        "TM77": "Psych Up",
        "TM78": "Bulldoze",
        "TM79": "Frost Breath",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Dragon Tail",
        "TM83": "Infestation",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Sleep Talk",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "TM93": "Wild Charge",
        "TM94": "Secret Power",
        "TM95": "Snarl",
        "TM96": "Nature Power",
        "TM97": "Dark Pulse",
        "TM98": "Power-Up Punch",
        "TM99": "Dazzling Gleam",
        "TM100": "Confide",
        "HM01": "Cut",
        "HM02": "Fly",
        "HM03": "Surf",
        "HM04": "Strength",
        "HM05": "Waterfall",
        "HM06": "Rock Smash",
        "HM07": "Dive",
    },
    "7": {
        "TM01": "Work Up",
        "TM02": "Dragon Claw",
        "TM03": "Psyshock",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Venoshock",
        "TM10": "Hidden Power",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Roost",
        "TM20": "Safeguard",
        "TM21": "Frustration",
        "TM22": "Solar Beam",
        "TM23": "Smack Down",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Return",
        "TM28": "Leech Life",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Sludge Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Flame Charge",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Low Sweep",
        "TM48": "Round",
        "TM49": "Echoed Voice",
        "TM50": "Overheat",
        "TM51": "Steel Wing",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Scald",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Sky Drop",
        "TM59": "Brutal Swing",
        "TM60": "Quash",
        "TM61": "Will-O-Wisp",
        "TM62": "Acrobatics",
        "TM63": "Embargo",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Smart Strike",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Aurora Veil",
        "TM71": "Stone Edge",
        "TM72": "Volt Switch",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Fly",
        "TM77": "Psych Up",
        "TM78": "Bulldoze",
        "TM79": "Frost Breath",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Dragon Tail",
        "TM83": "Infestation",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Sleep Talk",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "TM93": "Wild Charge",
        "TM94": "Surf",
        "TM95": "Snarl",
        "TM96": "Nature Power",
        "TM97": "Dark Pulse",
        "TM98": "Waterfall",
        "TM99": "Dazzling Gleam",
        "TM100": "Confide",
    },
    "8": {
        "TM00": "Mega Punch",
        "TM01": "Mega Kick",
        "TM02": "Pay Day",
        "TM03": "Fire Punch",
        "TM04": "Ice Punch",
        "TM05": "Thunder Punch",
        "TM06": "Fly",
        "TM07": "Pin Missile",
        "TM08": "Hyper Beam",
        "TM09": "Giga Impact",
        "TM10": "Magical Leaf",
        "TM11": "Solar Beam",
        "TM12": "Solar Blade",
        "TM13": "Fire Spin",
        "TM14": "Thunder Wave",
        "TM15": "Dig",
        "TM16": "Screech",
        "TM17": "Light Screen",
        "TM18": "Reflect",
        "TM19": "Safeguard",
        "TM20": "Self-Destruct",
        "TM21": "Rest",
        "TM22": "Rock Slide",
        "TM23": "Thief",
        "TM24": "Snore",
        "TM25": "Protect",
        "TM26": "Scary Face",
        "TM27": "Icy Wind",
        "TM28": "Giga Drain",
        "TM29": "Charm",
        "TM30": "Steel Wing",
        "TM31": "Attract",
        "TM32": "Sandstorm",
        "TM33": "Rain Dance",
        "TM34": "Sunny Day",
        "TM35": "Hail",
        "TM36": "Whirlpool",
        "TM37": "Beat Up",
        "TM38": "Will-O-Wisp",
        "TM39": "Facade",
        "TM40": "Swift",
        "TM41": "Helping Hand",
        "TM42": "Revenge",
        "TM43": "Brick Break",
        "TM44": "Imprison",
        "TM45": "Dive",
        "TM46": "Weather Ball",
        "TM47": "Fake Tears",
        "TM48": "Rock Tomb",
        "TM49": "Sand Tomb",
        "TM50": "Bullet Seed",
        "TM51": "Icicle Spear",
        "TM52": "Bounce",
        "TM53": "Mud Shot",
        "TM54": "Rock Blast",
        "TM55": "Brine",
        "TM56": "U-turn",
        "TM57": "Payback",
        "TM58": "Assurance",
        "TM59": "Fling",
        "TM60": "Power Swap",
        "TM61": "Guard Swap",
        "TM62": "Speed Swap",
        "TM63": "Drain Punch",
        "TM64": "Avalanche",
        "TM65": "Shadow Claw",
        "TM66": "Thunder Fang",
        "TM67": "Ice Fang",
        "TM68": "Fire Fang",
        "TM69": "Psycho Cut",
        "TM70": "Trick Room",
        "TM71": "Wonder Room",
        "TM72": "Magic Room",
        "TM73": "Cross Poison",
        "TM74": "Venoshock",
        "TM75": "Low Sweep",
        "TM76": "Round",
        "TM77": "Hex",
        "TM78": "Acrobatics",
        "TM79": "Retaliate",
        "TM80": "Volt Switch",
        "TM81": "Bulldoze",
        "TM82": "Electroweb",
        "TM83": "Razor Shell",
        "TM84": "Tail Slap",
        "TM85": "Snarl",
        "TM86": "Phantom Force",
        "TM87": "Draining Kiss",
        "TM88": "Grassy Terrain",
        "TM89": "Misty Terrain",
        "TM90": "Electric Terrain",
        "TM91": "Psychic Terrain",
        "TM92": "Mystical Fire",
        "TM93": "Eerie Impulse",
        "TM94": "False Swipe",
        "TM95": "Air Slash",
        "TM96": "Smart Strike",
        "TM97": "Brutal Swing",
        "TM98": "Stomping Tantrum",
        "TM99": "Breaking Swipe",
        "TR00": "Swords Dance",
        "TR01": "Body Slam",
        "TR02": "Flamethrower",
        "TR03": "Hydro Pump",
        "TR04": "Surf",
        "TR05": "Ice Beam",
        "TR06": "Blizzard",
        "TR07": "Low Kick",
        "TR08": "Thunderbolt",
        "TR09": "Thunder",
        "TR10": "Earthquake",
        "TR11": "Psychic",
        "TR12": "Agility",
        "TR13": "Focus Energy",
        "TR14": "Metronome",
        "TR15": "Fire Blast",
        "TR16": "Waterfall",
        "TR17": "Amnesia",
        "TR18": "Leech Life",
        "TR19": "Tri Attack",
        "TR20": "Substitute",
        "TR21": "Reversal",
        "TR22": "Sludge Bomb",
        "TR23": "Spikes",
        "TR24": "Outrage",
        "TR25": "Psyshock",
        "TR26": "Endure",
        "TR27": "Sleep Talk",
        "TR28": "Megahorn",
        "TR29": "Baton Pass",
        "TR30": "Encore",
        "TR31": "Iron Tail",
        "TR32": "Crunch",
        "TR33": "Shadow Ball",
        "TR34": "Future Sight",
        "TR35": "Uproar",
        "TR36": "Heat Wave",
        "TR37": "Taunt",
        "TR38": "Trick",
        "TR39": "Superpower",
        "TR40": "Skill Swap",
        "TR41": "Blaze Kick",
        "TR42": "Hyper Voice",
        "TR43": "Overheat",
        "TR44": "Cosmic Power",
        "TR45": "Muddy Water",
        "TR46": "Iron Defense",
        "TR47": "Dragon Claw",
        "TR48": "Bulk Up",
        "TR49": "Calm Mind",
        "TR50": "Leaf Blade",
        "TR51": "Dragon Dance",
        "TR52": "Gyro Ball",
        "TR53": "Close Combat",
        "TR54": "Toxic Spikes",
        "TR55": "Flare Blitz",
        "TR56": "Aura Sphere",
        "TR57": "Poison Jab",
        "TR58": "Dark Pulse",
        "TR59": "Seed Bomb",
        "TR60": "X-Scissor",
        "TR61": "Bug Buzz",
        "TR62": "Dragon Pulse",
        "TR63": "Power Gem",
        "TR64": "Focus Blast",
        "TR65": "Energy Ball",
        "TR66": "Brave Bird",
        "TR67": "Earth Power",
        "TR68": "Nasty Plot",
        "TR69": "Zen Headbutt",
        "TR70": "Flash Cannon",
        "TR71": "Leaf Storm",
        "TR72": "Power Whip",
        "TR73": "Gunk Shot",
        "TR74": "Iron Head",
        "TR75": "Stone Edge",
        "TR76": "Stealth Rock",
        "TR77": "Grass Knot",
        "TR78": "Sludge Wave",
        "TR79": "Heavy Slam",
        "TR80": "Electro Ball",
        "TR81": "Foul Play",
        "TR82": "Stored Power",
        "TR83": "Ally Switch",
        "TR84": "Scald",
        "TR85": "Work Up",
        "TR86": "Wild Charge",
        "TR87": "Drill Run",
        "TR88": "Heat Crash",
        "TR89": "Hurricane",
        "TR90": "Play Rough",
        "TR91": "Venom Drench",
        "TR92": "Dazzling Gleam",
        "TR93": "Darkest Lariat",
        "TR94": "High Horsepower",
        "TR95": "Throat Chop",
        "TR96": "Pollen Puff",
        "TR97": "Psychic Fangs",
        "TR98": "Liquidation",
        "TR99": "Body Press",
    },
    "8bdsp": {
        "TM01": "Focus Punch",
        "TM02": "Dragon Claw",
        "TM03": "Water Pulse",
        "TM04": "Calm Mind",
        "TM05": "Roar",
        "TM06": "Toxic",
        "TM07": "Hail",
        "TM08": "Bulk Up",
        "TM09": "Bullet Seed",
        "TM10": "Work Up",
        "TM11": "Sunny Day",
        "TM12": "Taunt",
        "TM13": "Ice Beam",
        "TM14": "Blizzard",
        "TM15": "Hyper Beam",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Rain Dance",
        "TM19": "Giga Drain",
        "TM20": "Safeguard",
        "TM21": "Dazzling Gleam",
        "TM22": "Solar Beam",
        "TM23": "Iron Tail",
        "TM24": "Thunderbolt",
        "TM25": "Thunder",
        "TM26": "Earthquake",
        "TM27": "Low Sweep",
        "TM28": "Dig",
        "TM29": "Psychic",
        "TM30": "Shadow Ball",
        "TM31": "Brick Break",
        "TM32": "Double Team",
        "TM33": "Reflect",
        "TM34": "Shock Wave",
        "TM35": "Flamethrower",
        "TM36": "Sludge Bomb",
        "TM37": "Sandstorm",
        "TM38": "Fire Blast",
        "TM39": "Rock Tomb",
        "TM40": "Aerial Ace",
        "TM41": "Torment",
        "TM42": "Facade",
        "TM43": "Volt Switch",
        "TM44": "Rest",
        "TM45": "Attract",
        "TM46": "Thief",
        "TM47": "Steel Wing",
        "TM48": "Skill Swap",
        "TM49": "Scald",
        "TM50": "Overheat",
        "TM51": "Roost",
        "TM52": "Focus Blast",
        "TM53": "Energy Ball",
        "TM54": "False Swipe",
        "TM55": "Brine",
        "TM56": "Fling",
        "TM57": "Charge Beam",
        "TM58": "Endure",
        "TM59": "Dragon Pulse",
        "TM60": "Drain Punch",
        "TM61": "Will-O-Wisp",
        "TM62": "Bug Buzz",
        "TM63": "Nasty Plot",
        "TM64": "Explosion",
        "TM65": "Shadow Claw",
        "TM66": "Payback",
        "TM67": "Recycle",
        "TM68": "Giga Impact",
        "TM69": "Rock Polish",
        "TM70": "Flash",
        "TM71": "Stone Edge",
        "TM72": "Avalanche",
        "TM73": "Thunder Wave",
        "TM74": "Gyro Ball",
        "TM75": "Swords Dance",
        "TM76": "Stealth Rock",
        "TM77": "Psych Up",
        "TM78": "Snarl",
        "TM79": "Dark Pulse",
        "TM80": "Rock Slide",
        "TM81": "X-Scissor",
        "TM82": "Sleep Talk",
        "TM83": "Bulldoze",
        "TM84": "Poison Jab",
        "TM85": "Dream Eater",
        "TM86": "Grass Knot",
        "TM87": "Swagger",
        "TM88": "Pluck",
        "TM89": "U-turn",
        "TM90": "Substitute",
        "TM91": "Flash Cannon",
        "TM92": "Trick Room",
        "TM93": "Cut",
        "TM94": "Fly",
        "TM95": "Surf",
        "TM96": "Strength",
        "TM97": "Defog",
        "TM98": "Rock Smash",
        "TM99": "Waterfall",
        "TM100": "Rock Climb",
    },
    "9": {
        "TM01": "Take Down",
        "TM02": "Charm",
        "TM03": "Fake Tears",
        "TM04": "Agility",
        "TM05": "Mud-Slap",
        "TM06": "Scary Face",
        "TM07": "Protect",
        "TM08": "Fire Fang",
        "TM09": "Thunder Fang",
        "TM10": "Ice Fang",
        "TM11": "Water Pulse",
        "TM12": "Low Kick",
        "TM13": "Acid Spray",
        "TM14": "Acrobatics",
        "TM15": "Struggle Bug",
        "TM16": "Psybeam",
        "TM17": "Confuse Ray",
        "TM18": "Thief",
        "TM19": "Disarming Voice",
        "TM20": "Trailblaze",
        "TM21": "Pounce",
        "TM22": "Chilling Water",
        "TM23": "Charge Beam",
        "TM24": "Fire Spin",
        "TM25": "Facade",
        "TM26": "Poison Tail",
        "TM27": "Aerial Ace",
        "TM28": "Bulldoze",
        "TM29": "Hex",
        "TM30": "Snarl",
        "TM31": "Metal Claw",
        "TM32": "Swift",
        "TM33": "Magical Leaf",
        "TM34": "Icy Wind",
        "TM35": "Mud Shot",
        "TM36": "Rock Tomb",
        "TM37": "Draining Kiss",
        "TM38": "Flame Charge",
        "TM39": "Low Sweep",
        "TM40": "Air Cutter",
        "TM41": "Stored Power",
        "TM42": "Night Shade",
        "TM43": "Fling",
        "TM44": "Dragon Tail",
        "TM45": "Venoshock",
        "TM46": "Avalanche",
        "TM47": "Endure",
        "TM48": "Volt Switch",
        "TM49": "Sunny Day",
        "TM50": "Rain Dance",
        "TM51": "Sandstorm",
        "TM52": "Snowscape",
        "TM53": "Smart Strike",
        "TM54": "Psyshock",
        "TM55": "Dig",
        "TM56": "Bullet Seed",
        "TM57": "False Swipe",
        "TM58": "Brick Break",
        "TM59": "Zen Headbutt",
        "TM60": "U-turn",
        "TM61": "Shadow Claw",
        "TM62": "Foul Play",
        "TM63": "Psychic Fangs",
        "TM64": "Bulk Up",
        "TM65": "Air Slash",
        "TM66": "Body Slam",
        "TM67": "Fire Punch",
        "TM68": "Thunder Punch",
        "TM69": "Ice Punch",
        "TM70": "Sleep Talk",
        "TM71": "Seed Bomb",
        "TM72": "Electro Ball",
        "TM73": "Drain Punch",
        "TM74": "Reflect",
        "TM75": "Light Screen",
        "TM76": "Rock Blast",
        "TM77": "Waterfall",
        "TM78": "Dragon Claw",
        "TM79": "Dazzling Gleam",
        "TM80": "Metronome",
        "TM81": "Grass Knot",
        "TM82": "Thunder Wave",
        "TM83": "Poison Jab",
        "TM84": "Stomping Tantrum",
        "TM85": "Rest",
        "TM86": "Rock Slide",
        "TM87": "Taunt",
        "TM88": "Swords Dance",
        "TM89": "Body Press",
        "TM90": "Spikes",
        "TM91": "Toxic Spikes",
        "TM92": "Imprison",
        "TM93": "Flash Cannon",
        "TM94": "Dark Pulse",
        "TM95": "Leech Life",
        "TM96": "Eerie Impulse",
        "TM97": "Fly",
        "TM98": "Skill Swap",
        "TM99": "Iron Head",
        "TM100": "Dragon Dance",
        "TM101": "Power Gem",
        "TM102": "Gunk Shot",
        "TM103": "Substitute",
        "TM104": "Iron Defense",
        "TM105": "X-Scissor",
        "TM106": "Drill Run",
        "TM107": "Will-O-Wisp",
        "TM108": "Crunch",
        "TM109": "Trick",
        "TM110": "Liquidation",
        "TM111": "Giga Drain",
        "TM112": "Aura Sphere",
        "TM113": "Tailwind",
        "TM114": "Shadow Ball",
        "TM115": "Dragon Pulse",
        "TM116": "Stealth Rock",
        "TM117": "Hyper Voice",
        "TM118": "Heat Wave",
        "TM119": "Energy Ball",
        "TM120": "Psychic",
        "TM121": "Heavy Slam",
        "TM122": "Encore",
        "TM123": "Surf",
        "TM124": "Ice Spinner",
        "TM125": "Flamethrower",
        "TM126": "Thunderbolt",
        "TM127": "Play Rough",
        "TM128": "Amnesia",
        "TM129": "Calm Mind",
        "TM130": "Helping Hand",
        "TM131": "Pollen Puff",
        "TM132": "Baton Pass",
        "TM133": "Earth Power",
        "TM134": "Reversal",
        "TM135": "Ice Beam",
        "TM136": "Electric Terrain",
        "TM137": "Grassy Terrain",
        "TM138": "Psychic Terrain",
        "TM139": "Misty Terrain",
        "TM140": "Nasty Plot",
        "TM141": "Fire Blast",
        "TM142": "Hydro Pump",
        "TM143": "Blizzard",
        "TM144": "Fire Pledge",
        "TM145": "Water Pledge",
        "TM146": "Grass Pledge",
        "TM147": "Wild Charge",
        "TM148": "Sludge Bomb",
        "TM149": "Earthquake",
        "TM150": "Stone Edge",
        "TM151": "Phantom Force",
        "TM152": "Giga Impact",
        "TM153": "Blast Burn",
        "TM154": "Hydro Cannon",
        "TM155": "Frenzy Plant",
        "TM156": "Outrage",
        "TM157": "Overheat",
        "TM158": "Focus Blast",
        "TM159": "Leaf Storm",
        "TM160": "Hurricane",
        "TM161": "Trick Room",
        "TM162": "Bug Buzz",
        "TM163": "Hyper Beam",
        "TM164": "Brave Bird",
        "TM165": "Flare Blitz",
        "TM166": "Thunder",
        "TM167": "Close Combat",
        "TM168": "Solar Beam",
        "TM169": "Draco Meteor",
        "TM170": "Steel Beam",
        "TM171": "Tera Blast",
        "TM172": "Roar",
        "TM173": "Charge",
        "TM174": "Haze",
        "TM175": "Toxic",
        "TM176": "Sand Tomb",
        "TM177": "Spite",
        "TM178": "Gravity",
        "TM179": "Smack Down",
        "TM180": "Gyro Ball",
        "TM181": "Knock Off",
        "TM182": "Bug Bite",
        "TM183": "Super Fang",
        "TM184": "Vacuum Wave",
        "TM185": "Lunge",
        "TM186": "High Horsepower",
        "TM187": "Icicle Spear",
        "TM188": "Scald",
        "TM189": "Heat Crash",
        "TM190": "Solar Blade",
        "TM191": "Uproar",
        "TM192": "Focus Punch",
        "TM193": "Weather Ball",
        "TM194": "Grassy Glide",
        "TM195": "Burning Jealousy",
        "TM196": "Flip Turn",
        "TM197": "Dual Wingbeat",
        "TM198": "Poltergeist",
        "TM199": "Lash Out",
        "TM200": "Scale Shot",
        "TM201": "Misty Explosion",
        "TM202": "Pain Split",
        "TM203": "Psych Up",
        "TM204": "Double-Edge",
        "TM205": "Endeavor",
        "TM206": "Petal Blizzard",
        "TM207": "Temper Flare",
        "TM208": "Whirlpool",
        "TM209": "Muddy Water",
        "TM210": "Supercell Slam",
        "TM211": "Electroweb",
        "TM212": "Triple Axel",
        "TM213": "Coaching",
        "TM214": "Sludge Wave",
        "TM215": "Scorching Sands",
        "TM216": "Feather Dance",
        "TM217": "Future Sight",
        "TM218": "Expanding Force",
        "TM219": "Skitter Smack",
        "TM220": "Meteor Beam",
        "TM221": "Throat Chop",
        "TM222": "Breaking Swipe",
        "TM223": "Metal Sound",
        "TM224": "Curse",
        "TM225": "Hard Press",
        "TM226": "Dragon Cheer",
        "TM227": "Alluring Voice",
        "TM228": "Psychic Noise",
        "TM229": "Upper Hand",
    },
    "9za": {
        "TM01": "Headbutt",
        "TM02": "Dragon Claw",
        "TM03": "Psyshock",
        "TM04": "Rock Smash",
        "TM05": "Roar",
        "TM06": "Calm Mind",
        "TM07": "Toxic",
        "TM08": "Thunder Wave",
        "TM09": "Flip Turn",
        "TM10": "Brick Break",
        "TM11": "Bulk Up",
        "TM12": "Rock Slide",
        "TM13": "Ice Beam",
        "TM14": "Fire Fang",
        "TM15": "Ice Fang",
        "TM16": "Light Screen",
        "TM17": "Protect",
        "TM18": "Power-Up Punch",
        "TM19": "Power Gem",
        "TM20": "Play Rough",
        "TM21": "Thunder Fang",
        "TM22": "Aerial Ace",
        "TM23": "Thunder Punch",
        "TM24": "Ice Punch",
        "TM25": "Crunch",
        "TM26": "Energy Ball",
        "TM27": "Swift",
        "TM28": "Dig",
        "TM29": "Fire Punch",
        "TM30": "Swords Dance",
        "TM31": "Reflect",
        "TM32": "Double Team",
        "TM33": "Body Slam",
        "TM34": "Night Slash",
        "TM35": "Endure",
        "TM36": "Rock Tomb",
        "TM37": "Stealth Rock",
        "TM38": "Fire Blast",
        "TM39": "Discharge",
        "TM40": "Bullet Seed",
        "TM41": "Water Pulse",
        "TM42": "Giga Drain",
        "TM43": "Fly",
        "TM44": "Hyper Beam",
        "TM45": "Knock Off",
        "TM46": "Mud Shot",
        "TM47": "Agility",
        "TM48": "Self-Destruct",
        "TM49": "Icy Wind",
        "TM50": "Overheat",
        "TM51": "Safeguard",
        "TM52": "Earth Power",
        "TM53": "Sludge Bomb",
        "TM54": "Draco Meteor",
        "TM55": "Giga Impact",
        "TM56": "Double-Edge",
        "TM57": "Will-O-Wisp",
        "TM58": "Iron Head",
        "TM59": "Zen Headbutt",
        "TM60": "Future Sight",
        "TM61": "Shadow Claw",
        "TM62": "Flamethrower",
        "TM63": "Psychic",
        "TM64": "Solar Beam",
        "TM65": "Stone Edge",
        "TM66": "Volt Switch",
        "TM67": "Thunderbolt",
        "TM68": "Heat Wave",
        "TM69": "Earthquake",
        "TM70": "Whirlpool",
        "TM71": "Hyper Voice",
        "TM72": "Fire Spin",
        "TM73": "Surf",
        "TM74": "Shadow Ball",
        "TM75": "Dragon Pulse",
        "TM76": "Liquidation",
        "TM77": "Poison Jab",
        "TM78": "Bulldoze",
        "TM79": "Hurricane",
        "TM80": "Iron Defense",
        "TM81": "X-Scissor",
        "TM82": "U-turn",
        "TM83": "Nasty Plot",
        "TM84": "Flash Cannon",
        "TM85": "Substitute",
        "TM86": "Wild Charge",
        "TM87": "Iron Tail",
        "TM88": "Spikes",
        "TM89": "Toxic Spikes",
        "TM90": "Dark Pulse",
        "TM91": "Curse",
        "TM92": "Dazzling Gleam",
        "TM93": "Outrage",
        "TM94": "Whirlwind",
        "TM95": "Taunt",
        "TM96": "Hydro Pump",
        "TM97": "Heal Block",
        "TM98": "Waterfall",
        "TM99": "Metronome",
        "TM100": "Gunk Shot",
        "TM101": "Electroweb",
        "TM102": "Focus Blast",
        "TM103": "Work Up",
        "TM104": "Flare Blitz",
        "TM105": "Blizzard",
        "TM106": "Thunder",
        "TM107": "Close Combat",
        "TM108": "Comet Punch",
        "TM109": "Facade",
        "TM110": "Chilling Water",
        "TM111": "Sing",
        "TM112": "Acid Spray",
        "TM113": "Low Sweep",
        "TM114": "Flame Charge",
        "TM115": "Trailblaze",
        "TM116": "Pay Day",
        "TM117": "Silver Wind",
        "TM118": "Shadow Punch",
        "TM119": "Ominous Wind",
        "TM120": "Ancient Power",
        "TM121": "Torment",
        "TM122": "False Swipe",
        "TM123": "Poison Fang",
        "TM124": "Psychic Fangs",
        "TM125": "Mimic",
        "TM126": "Magnet Bomb",
        "TM127": "Dream Eater",
        "TM128": "Seed Bomb",
        "TM129": "Circle Throw",
        "TM130": "Charge Beam",
        "TM131": "Drain Punch",
        "TM132": "Double Hit",
        "TM133": "Blaze Kick",
        "TM134": "Dual Wingbeat",
        "TM135": "Dual Chop",
        "TM136": "Scorching Sands",
        "TM137": "Storm Throw",
        "TM138": "Frost Breath",
        "TM139": "Swagger",
        "TM140": "Muddy Water",
        "TM141": "Fake Out",
        "TM142": "First Impression",
        "TM143": "Scale Shot",
        "TM144": "Triple Axel",
        "TM145": "Razor Wind",
        "TM146": "Skull Bash",
        "TM147": "Tri Attack",
        "TM148": "Scald",
        "TM149": "Icicle Spear",
        "TM150": "Vacuum Wave",
        "TM151": "Petal Dance",
        "TM152": "Solar Blade",
        "TM153": "Sky Attack",
        "TM154": "Fissure",
        "TM155": "Sheer Cold",
        "TM156": "Meteor Beam",
        "TM157": "Steel Beam",
        "TM158": "Blast Burn",
        "TM159": "Hydro Cannon",
        "TM160": "Frenzy Plant",
    },
}
