const unobtainable_moves = {
    "Banned": [
        "Double Team",
        "Minimize",
    ],
    "Red and Blue": [

    ],
    "Yellow": [

    ],
    "Gold and Silver": [
        "Psych Up",
    ],
    "Crystal": [
        "Psych Up",
    ],
    "Emerald": [
        "Snatch",
        "Softboiled",
        "Seismic Toss",
        "Dream Eater",
        "Mega Punch",
        "Mega Kick",
        "Body Slam",
        "Rock Slide",
        "Counter",
        "Thunder Wave",
        "Defense Curl",
        "Snore",
        "Mud-Slap",
        "Swift",
        "Icy Wind",
        "Endure",
        "Psych Up",
        "Ice Punch",
        "Fire Punch",
        "ThunderPunch",
    ],
    "FireRed and LeafGreen": [
        "Hidden Power",
        "Sludge Bomb",
        "Facade",
        "Body Slam",
        "Swords Dance",
    ],
    "Diamond and Pearl": [
        "Calm Mind",
        "Bulk Up",
        "Facade",
        "Overheat",
        "Energy Ball",
        "Will-O-Wisp",
        "Thunder Wave",
        "AncientPower",
        "Aqua Tail",
        "Bounce",
        "Earth Power",
        "Endeavor",
        "Gastro Acid",
        "Gunk Shot",
        "Heat Wave",
        "Iron Defense",
        "Iron Head",
        "Mud-Slap",
        "Outrage",
        "Rollout",
        "Seed Bomb",
        "Signal Beam",
        "Superpower",
        "Twister",
    ],
    "Platinum": [
        "Calm Mind",
        "Bulk Up",
        "Sandstorm",
        "Facade",
        "Overheat",
        "Energy Ball",
        "Will-O-Wisp",
        "Thunder Wave",
        "AncientPower",
        "Aqua Tail",
        "Bounce",
        "Earth Power",
        "Endeavor",
        "Gastro Acid",
        "Gunk Shot",
        "Heat Wave",
        "Iron Defense",
        "Iron Head",
        "Mud-Slap",
        "Outrage",
        "Rollout",
        "Seed Bomb",
        "Signal Beam",
        "Superpower",
        "Twister",
    ],
    "HeartGold and SoulSilver": [
        "Calm Mind",
        "Toxic",
        "Bulk Up",
        "Brick Break",
        "Energy Ball",
        "Will-O-Wisp",
        "Stone Edge",
        "Thunder Wave",
        "X-Scissor",
        "Air Cutter",
        "Bug Bite",
        "Dive",
        "Fire Punch",
        "Fury Cutter",
        "Ice Punch",
        "Icy Wind",
        "Knock Off",
        "Ominous Wind",
        "Sucker Punch",
        "ThunderPunch",
        "Trick",
        "Vacuum Wave",
        "Zen Headbutt",
        "AncientPower",
        "Aqua Tail",
        "Bounce",
        "Earth Power",
        "Endeavor",
        "Gastro Acid",
        "Gunk Shot",
        "Heat Wave",
        "Iron Defense",
        "Iron Head",
        "Low Kick",
        "Mud-Slap",
        "Outrage",
        "Pain Split",
        "Rollout",
        "Seed Bomb"	,
        "Signal Beam",
        "Sky Attack",
        "Super Fang",
        "Superpower",
        "Twister",
        "Block",
        "Gravity",
        "Heal Bell",
        "Helping Hand",
        "Last Resort",
        "Magic Coat",
        "Magnet Rise",
        "Role Play",
        "Snore",
        "Spite",
        "String Shot", 
        "Swift",
        "Synthesis",
        "Tailwind",
        "Uproar",
        "Worry Seed",
    ],
    "Black": [
        "Hone Claws",
        "Psyshock",
        "Calm Mind",
        "Bulk Up",
        "Venoshock",
        "Ice Beam",
        "Smack Down",
        "Earthquake",
        "Psychic",
        "Double Team",
        "Sludge Wave",
        "Flamethrower",
        "Round",
        "Overheat",
        "Ally Switch",
        "Energy Ball",
        "Incinerate",
        "Quash",
        "Explosion",
        "Rock Polish",
        "Stone Edge",
        "Swords Dance",
        "Psych Up",
        "Dream Eater",
        "Swagger",
        "Pluck",
        "U-Turn",
        "Trick Room",
        "Snarl",
        "Dive",
    ],
    "White": [
        "Hone Claws",
        "Psyshock",
        "Calm Mind",
        "Bulk Up",
        "Venoshock",
        "Ice Beam",
        "Smack Down",
        "Earthquake",
        "Psychic",
        "Double Team",
        "Sludge Wave",
        "Flamethrower",
        "Round",
        "Overheat",
        "Ally Switch",
        "Energy Ball",
        "Incinerate",
        "Quash",
        "Explosion",
        "Rock Polish",
        "Stone Edge",
        "Swords Dance",
        "Psych Up",
        "Dream Eater",
        "Swagger",
        "Pluck",
        "U-Turn",
        "Trick Room",
        "Snarl",
        "Dive",
    ],
    "Black 2": [
        "Dragon Claw",
        "Calm Mind",
        "Bulk Up",
        "Hidden Power",
        "Protect",
        "Telekinesis",
        "Solar Beam",
        "Smack Down",
        "Earthquake",
        "Brick Break",
        "Double Team",
        "Sludge Wave",
        "Sludge Bomb",
        "Low Sweep",
        "Round",
        "Overheat",
        "Ally Switch",
        "Focus Blast",
        "Incinerate",
        "Quash",
        "Explosion",
        "Stone Edge",
        "Swords Dance",
        "Psych Up",
        "Frost Breath",
        "Poison Jab",
        "Dream Eater",
        "Grass Knot",
        "Swagger",
        "Pluck",
        "U-Turn",
        "Substitute",
        "Flash Cannon",
        "Worry Seed",	 
        "Gastro Acid",	 
        "Helping Hand", 
        "After You",	 
        "Magic Room",	 
        "Wonder Room",	 
        "Spite",	     
        "Recycle",	     
        "Trick",	     
        "Stealth",      
        "Outrage",	     
        "Endeavor",	 
        "Sleep Talk",	 
        "Skill Swap",	 
        "Snatch",	     
    ],
    "White 2": [
        "Dragon Claw",
        "Calm Mind",
        "Bulk Up",
        "Hidden Power",
        "Protect",
        "Telekinesis",
        "Solar Beam",
        "Smack Down",
        "Earthquake",
        "Brick Break",
        "Double Team",
        "Sludge Wave",
        "Sludge Bomb",
        "Low Sweep",
        "Round",
        "Overheat",
        "Ally Switch",
        "Focus Blast",
        "Incinerate",
        "Quash",
        "Explosion",
        "Stone Edge",
        "Swords Dance",
        "Psych Up",
        "Frost Breath",
        "Poison Jab",
        "Dream Eater",
        "Grass Knot",
        "Swagger",
        "Pluck",
        "U-Turn",
        "Substitute",
        "Flash Cannon",
        "Worry Seed",	 
        "Gastro Acid",	 
        "Helping Hand", 
        "After You",	 
        "Magic Room",	 
        "Wonder Room",	 
        "Spite",	     
        "Recycle",	     
        "Trick",	     
        "Stealth",      
        "Outrage",	     
        "Endeavor",	 
        "Sleep Talk",	 
        "Skill Swap",	 
        "Snatch",	 
    ],
    "X and Y": [
        "Roar",
        "Light Screen",
        "Smack Down",
        "Reflect",
        "Sludge Wave",
        "Round",
        "Overheat",
        "Steel Wing",
        "Sky Drop",
        "Incinerate",
        "Quash",
        "Explosion",
        "Retaliate",
        "Giga Impact",
        "Volt Switch",
        "Dream Eater",
        "Swagger",
        "Flash Cannon",
        "Wild Charge",

    ],
    "Omega Ruby and Alpha Sapphire": [
        "Explosion",
        "Swagger",
        "Payback",
        "Gyro Ball",
        "Poison Jab",
        "Substitute",
        "Flash Cannon",
        "Snarl",
        "Bind",
        "Snore",
        "Water Pulse",
        "Shock Wave",
        "Bug Bite",
        "Covet",
        "Low Kick",
        "Signal Beam",
        "Giga Drain",
        "Thunder Punch",
        "Fire Punch",
        "Ice Punch",
        "Drain Punch",
        "Knock Off",
        "Super Fang",
        "Dual Chop",
        "Endeavor",
        "Uproar",
        "Iron Tail",
        "Bounce",
        "Drill Run",
        "Iron Head",
        "Zen Headbutt",
        "Aqua Tail",
        "Dragon Pulse",
        "Seed Bomb",
        "Heat Wave",
        "Last Resort",
        "Hyper Voice",
        "Foul Play",
        "Earth Power",
        "Outrage",
        "Superpower",
        "Gunk Shot",
        "Sky Attack",
        "Focus Punch",
        "Block",
        "Skill Swap",
        "Synthesis",
        "Role Play",
        "Pain Split",
        "Gastro Acid",
        "Worry Seed",
        "Spite",
        "After You",
        "Helping Hand",
        "Trick",
        "Recycle",
        "Snatch",
        "Magic Coat",
        "Magnet Rise",
        "Iron Defense",
        "Heal Bell",
        "Tailwind",
        "Magic Room",
        "Wonder Room",
        "Stealth Rock",
        "Gravity",
        "Electroweb",
        "Icy Wind",
    ],
}