export const encounters_by_pokemon = {
    "Abra": [
        {location: "Hau'oli City — Shopping District", method: "Walk", min_level: 5, max_level: 8, chance: 25},
        {location: "Route 2 — South", method: "Walk", min_level: 7, max_level: 10, chance: 20},
    ],
    "Absol": [
        {location: "Mount Lanakila — Cave", method: "Walk", min_level: 42, max_level: 45, chance: 10},
        {location: "Mount Lanakila — Outside", method: "Walk", min_level: 42, max_level: 45, chance: 20},
        {location: "Route 14", method: "Walk", min_level: 28, max_level: 31, chance: 10},
        {location: "Tapu Village", method: "Walk", min_level: 28, max_level: 31, chance: 10},
    ],
    "Aerodactyl": [
        {location: "Seafolk Village — Huntail Boat", method: "Gift", min_level: 40, max_level: 40, chance: 100},
    ],
    "Alomomola": [
        {location: "Brooklet Hill — Totems Den", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 20},
        {location: "Brooklet Hill — Totems Den", method: "Super Rod", min_level: 10, max_level: 15, chance: 1},
    ],
    "Araquanid": [
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 20},
    ],
    "Archen": [
        {location: "Route 8 — Fossil Restoration Center", method: "Gift", min_level: 15, max_level: 15, chance: 100},
    ],
    "Ariados": [
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 10", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 17 — West", method: "Walk", min_level: 31, max_level: 34, chance: 20},
        {location: "Ula’ula Meadow", method: "Walk", min_level: 31, max_level: 34, chance: 20},
    ],
    "Axew": [
        {location: "Mount Hokulani — Main", method: "Island Scan", min_level: 28, max_level: 28, chance: 100},
    ],
    "Bagon": [
        {location: "Kala’e Bay", method: "Walk", min_level: 15, max_level: 18, chance: 10},
        {location: "Route 3 — South", method: "Walk", min_level: 9, max_level: 12, chance: 1},
    ],
    "Barboach": [
        {location: "Paniola Town", method: "Bubbling Spots", min_level: 10, max_level: 18, chance: 50},
        {location: "Paniola Town", method: "Super Rod", min_level: 10, max_level: 18, chance: 1},
        {location: "Poni Gauntlet", method: "Bubbling Spots", min_level: 10, max_level: 59, chance: 40},
        {location: "Poni Gauntlet", method: "Super Rod", min_level: 10, max_level: 59, chance: 40},
        {location: "Poni Meadow", method: "Bubbling Spots", min_level: 10, max_level: 57, chance: 40},
        {location: "Poni Meadow", method: "Super Rod", min_level: 10, max_level: 57, chance: 40},
        {location: "Seaward Cave", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 50},
        {location: "Seaward Cave", method: "Super Rod", min_level: 10, max_level: 15, chance: 1},
        {location: "Vast Poni Canyon — Northwest", method: "Bubbling Spots", min_level: 10, max_level: 44, chance: 40},
        {location: "Vast Poni Canyon — Northwest", method: "Super Rod", min_level: 10, max_level: 44, chance: 40},
    ],
    "Beldum": [
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 10},
    ],
    "Bellsprout": [
        {location: "Route 5", method: "Island Scan", min_level: 16, max_level: 16, chance: 100},
    ],
    "Bewear": [
        {location: "Poni Gauntlet", method: "Walk", min_level: 56, max_level: 59, chance: 5},
    ],
    "Boldore": [
        {location: "Vast Poni Canyon — Inside", method: "Walk", min_level: 41, max_level: 44, chance: 30},
        {location: "Vast Poni Canyon — Northwest", method: "Walk", min_level: 41, max_level: 44, chance: 30},
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 10},
    ],
    "Bonsly": [
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 10},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 15},
    ],
    "Bounsweet": [
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 40},
        {location: "Route 5", method: "NPC Trade", min_level: 16, max_level: 16, chance: 100},
    ],
    "Braviary": [
        {location: "Poni Plains — North", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 30},
    ],
    "Bruxish": [
        {location: "Route 13", method: "Super Rod", min_level: 10, max_level: 30, chance: 1},
        {location: "Route 14", method: "Bubbling Spots", min_level: 10, max_level: 31, chance: 20},
        {location: "Route 14", method: "Super Rod", min_level: 10, max_level: 31, chance: 1},
        {location: "Route 15 — Main", method: "Bubbling Spots", min_level: 10, max_level: 33, chance: 20},
        {location: "Route 15 — Main", method: "Super Rod", min_level: 10, max_level: 33, chance: 1},
        {location: "Secluded Shore", method: "Super Rod", min_level: 10, max_level: 30, chance: 1},
        {location: "Tapu Village", method: "Bubbling Spots", min_level: 10, max_level: 31, chance: 20},
        {location: "Tapu Village", method: "Super Rod", min_level: 10, max_level: 31, chance: 1},
    ],
    "Butterfree": [
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Melemele Meadow", method: "SOS Encounter", min_level: 9, max_level: 12, chance: 15},
        {location: "Melemele Meadow", method: "Walk", min_level: 9, max_level: 12, chance: 1},
        {location: "Route 5", method: "SOS Encounter", min_level: 13, max_level: 16, chance: 15},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 1},
    ],
    "Buzzwole": [
        {location: "Melemele Meadow", method: "Static", min_level: 65, max_level: 65, chance: 100},
        {location: "Melemele Meadow", method: "Walk", min_level: 65, max_level: 65, chance: 100},
    ],
    "Carbink": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
        {location: "Ten Carat Hill — Farthest Hollow", method: "Walk", min_level: 10, max_level: 13, chance: 20},
        {location: "Ten Carat Hill — Inside", method: "Walk", min_level: 10, max_level: 13, chance: 20},
        {location: "Vast Poni Canyon — Inside", method: "Walk", min_level: 41, max_level: 44, chance: 20},
        {location: "Vast Poni Canyon — Northwest", method: "Walk", min_level: 41, max_level: 44, chance: 20},
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 15},
    ],
    "Castform": [
        {location: "Exeggutor Island", method: "SOS Encounter", min_level: 40, max_level: 43, chance: 11},
        {location: "Exeggutor Island", method: "SOS Encounter", min_level: 40, max_level: 43, chance: 1},
        {location: "Haina Desert", method: "SOS (Bubbling Spot)", min_level: 28, max_level: 31, chance: 10},
        {location: "Haina Desert", method: "SOS (Bubbling Spot)", min_level: 28, max_level: 31, chance: 1},
        {location: "Haina Desert", method: "SOS Encounter", min_level: 28, max_level: 31, chance: 10},
        {location: "Haina Desert", method: "SOS Encounter", min_level: 28, max_level: 31, chance: 1},
        {location: "Lush Jungle — North", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 11},
        {location: "Lush Jungle — North", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 1},
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 11},
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 1},
        {location: "Lush Jungle — West", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 11},
        {location: "Lush Jungle — West", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 1},
        {location: "Malie Garden", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 11},
        {location: "Mount Lanakila — Outside", method: "SOS Encounter", min_level: 42, max_level: 45, chance: 11},
        {location: "Mount Lanakila — Outside", method: "SOS Encounter", min_level: 42, max_level: 45, chance: 1},
        {location: "Route 17 — Northeast", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 100},
        {location: "Route 17 — Northeast", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 10},
        {location: "Route 17 — West", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 10},
        {location: "Route 17 — West", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 1},
        {location: "Tapu Village", method: "SOS Encounter", min_level: 28, max_level: 31, chance: 10},
        {location: "Tapu Village", method: "SOS Encounter", min_level: 28, max_level: 31, chance: 1},
    ],
    "Caterpie": [
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 10},
        {location: "Melemele Meadow", method: "SOS Encounter", min_level: 9, max_level: 12, chance: 15},
        {location: "Melemele Meadow", method: "Walk", min_level: 9, max_level: 12, chance: 10},
        {location: "Route 1 — East", method: "Walk", min_level: 2, max_level: 3, chance: 20},
        {location: "Route 1 — South", method: "SOS Encounter", min_level: 10, max_level: 13, chance: 15},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 10},
        {location: "Route 1 — West", method: "SOS Encounter", min_level: 3, max_level: 5, chance: 15},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 10},
        {location: "Route 5", method: "SOS Encounter", min_level: 13, max_level: 16, chance: 15},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 10},
    ],
    "Celesteela": [
        {location: "Haina Desert", method: "Static", min_level: 65, max_level: 65, chance: 100},
        {location: "Haina Desert", method: "Walk", min_level: 65, max_level: 65, chance: 100},
        {location: "Malie Garden", method: "Static", min_level: 65, max_level: 65, chance: 100},
        {location: "Malie Garden", method: "Walk", min_level: 65, max_level: 65, chance: 100},
    ],
    "Chansey": [
        {location: "Blush Mountain", method: "SOS Encounter", min_level: 26, max_level: 29, chance: 15},
        {location: "Mount Hokulani — Main", method: "SOS Encounter", min_level: 25, max_level: 28, chance: 15},
        {location: "Poni Grove", method: "SOS Encounter", min_level: 52, max_level: 55, chance: 15},
        {location: "Route 12", method: "SOS Encounter", min_level: 26, max_level: 29, chance: 15},
    ],
    "Charjabug": [
        {location: "Blush Mountain", method: "Walk", min_level: 26, max_level: 29, chance: 10},
    ],
    "Chikorita": [
        {location: "Route 2 — Main", method: "Island Scan", min_level: 10, max_level: 10, chance: 100},
    ],
    "Chinchou": [
        {location: "Route 8 — Main", method: "Bubbling Spots", min_level: 10, max_level: 25, chance: 20},
        {location: "Route 8 — Main", method: "Super Rod", min_level: 10, max_level: 20, chance: 1},
    ],
    "Clefairy": [
        {location: "Mount Hokulani — Main", method: "SOS Encounter", min_level: 25, max_level: 28, chance: 15},
    ],
    "Cleffa": [
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 10},
    ],
    "Comfey": [
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 5},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 5},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 5},
    ],
    "Conkeldurr": [
        {location: "Poni Plains — Center", method: "Island Scan", min_level: 57, max_level: 57, chance: 100},
    ],
    "Corsola": [
        {location: "Melemele Sea", method: "Bubbling Spots", min_level: 10, max_level: 18, chance: 20},
        {location: "Melemele Sea", method: "Super Rod", min_level: 10, max_level: 18, chance: 1},
        {location: "Route 9 — Main", method: "Super Rod", min_level: 10, max_level: 23, chance: 5},
    ],
    "Cosmog": [
        {location: "Lake of the Moone", method: "Gift", min_level: 5, max_level: 5, chance: 100},
        {location: "Lake of the Sunne", method: "Gift", min_level: 5, max_level: 5, chance: 100},
    ],
    "Cottonee": [
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 10},
        {location: "Melemele Meadow", method: "Walk", min_level: 9, max_level: 12, chance: 30},
        {location: "Poni Meadow", method: "Walk", min_level: 54, max_level: 57, chance: 50},
        {location: "Poni Plains — Center", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 70},
        {location: "Poni Plains — Center", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Ula’ula Meadow", method: "Walk", min_level: 31, max_level: 34, chance: 30},
    ],
    "Crabrawler": [
        {location: "Berry Fields", method: "Berry Piles", min_level: 7, max_level: 10, chance: 100},
        {location: "Poni Plains — West", method: "Berry Piles", min_level: 54, max_level: 57, chance: 100},
        {location: "Poni Wilds", method: "Berry Piles", min_level: 40, max_level: 43, chance: 100},
        {location: "Route 10", method: "Berry Piles", min_level: 24, max_level: 27, chance: 100},
        {location: "Route 12", method: "Berry Piles", min_level: 27, max_level: 30, chance: 100},
        {location: "Route 15 — Main", method: "Berry Piles", min_level: 30, max_level: 33, chance: 100},
        {location: "Route 16 — Main", method: "Berry Piles", min_level: 30, max_level: 33, chance: 100},
        {location: "Route 17 — West", method: "Berry Piles", min_level: 31, max_level: 34, chance: 100},
        {location: "Route 2 — South", method: "Berry Piles", min_level: 7, max_level: 10, chance: 100},
        {location: "Route 3 — South", method: "Berry Piles", min_level: 9, max_level: 12, chance: 100},
        {location: "Route 4", method: "Berry Piles", min_level: 11, max_level: 14, chance: 100},
        {location: "Route 5", method: "Berry Piles", min_level: 13, max_level: 16, chance: 100},
        {location: "Route 8 — Main", method: "Berry Piles", min_level: 17, max_level: 20, chance: 100},
    ],
    "Cranidos": [
        {location: "Route 8 — Fossil Restoration Center", method: "Gift", min_level: 15, max_level: 15, chance: 100},
    ],
    "Crobat": [
        {location: "Resolution Cave", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
    ],
    "Cubone": [
        {location: "Wela Volcano Park", method: "Walk", min_level: 16, max_level: 19, chance: 24},
    ],
    "Cutiefly": [
        {location: "Melemele Meadow", method: "Walk", min_level: 9, max_level: 12, chance: 30},
        {location: "Route 2 — North", method: "Walk", min_level: 7, max_level: 10, chance: 20},
        {location: "Route 3 — North", method: "Walk", min_level: 9, max_level: 12, chance: 20},
        {location: "Route 3 — South", method: "Walk", min_level: 9, max_level: 12, chance: 20},
    ],
    "Cyndaquil": [
        {location: "Route 3 — Main", method: "Island Scan", min_level: 12, max_level: 12, chance: 100},
    ],
    "Deino": [
        {location: "Ten Carat Hill — Inside", method: "Island Scan", min_level: 13, max_level: 13, chance: 100},
    ],
    "Delibird": [
        {location: "Route 3 — North", method: "Walk", min_level: 9, max_level: 12, chance: 10},
    ],
    "Dewpider": [
        {location: "Brooklet Hill — North", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Brooklet Hill — South", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Brooklet Hill — South", method: "Walk", min_level: 14, max_level: 17, chance: 20},
    ],
    "Dhelmise": [
        {location: "Seafolk Village — Main", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 10},
        {location: "Seafolk Village — Main", method: "Super Rod", min_level: 10, max_level: 43, chance: 1},
    ],
    "Ditto": [
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 10},
    ],
    "Dragonair": [
        {location: "Poni Gauntlet", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Gauntlet", method: "SOS Encounter", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Meadow", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 57, chance: 15},
        {location: "Poni Meadow", method: "SOS Encounter", min_level: 10, max_level: 57, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 44, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS Encounter", min_level: 10, max_level: 44, chance: 15},
    ],
    "Dragonite": [
        {location: "Poni Gauntlet", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Gauntlet", method: "SOS Encounter", min_level: 10, max_level: 59, chance: 15},
    ],
    "Drampa": [
        {location: "Mount Lanakila — Cave", method: "Walk", min_level: 42, max_level: 45, chance: 10},
    ],
    "Dratini": [
        {location: "Poni Gauntlet", method: "Bubbling Spots", min_level: 10, max_level: 59, chance: 10},
        {location: "Poni Gauntlet", method: "Super Rod", min_level: 10, max_level: 59, chance: 1},
        {location: "Poni Meadow", method: "Bubbling Spots", min_level: 10, max_level: 57, chance: 10},
        {location: "Poni Meadow", method: "Super Rod", min_level: 10, max_level: 57, chance: 1},
        {location: "Vast Poni Canyon — Northwest", method: "Bubbling Spots", min_level: 10, max_level: 44, chance: 10},
        {location: "Vast Poni Canyon — Northwest", method: "Super Rod", min_level: 10, max_level: 44, chance: 1},
    ],
    "Drifblim": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 3},
    ],
    "Drifloon": [
        {location: "Hau’oli Cemetery", method: "Walk", min_level: 7, max_level: 10, chance: 30},
    ],
    "Drowzee": [
        {location: "Route 2 — South", method: "Walk", min_level: 7, max_level: 10, chance: 20},
    ],
    "Duosion": [
        {location: "Route 16 — Main", method: "Island Scan", min_level: 33, max_level: 33, chance: 100},
    ],
    "Eelektross": [
        {location: "Poni Grove", method: "Island Scan", min_level: 55, max_level: 55, chance: 100},
    ],
    "Eevee": [
        {location: "Paniola Ranch", method: "Gift", min_level: 1, max_level: 1, chance: 100},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 5},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 5},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 5},
    ],
    "Electabuzz": [
        {location: "Blush Mountain", method: "SOS Encounter", min_level: 26, max_level: 29, chance: 15},
        {location: "Route 12", method: "SOS Encounter", min_level: 26, max_level: 29, chance: 15},
    ],
    "Electrode": [
        {location: "New Mauville", method: "Static", min_level: 30, max_level: 30, chance: 100},
    ],
    "Elekid": [
        {location: "Blush Mountain", method: "Walk", min_level: 26, max_level: 29, chance: 10},
        {location: "Route 12", method: "Walk", min_level: 26, max_level: 29, chance: 10},
    ],
    "Emboar": [
        {location: "Ancient Poni Path", method: "Island Scan", min_level: 43, max_level: 43, chance: 100},
    ],
    "Emolga": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 7},
        {location: "Poni Plains — West", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 20},
    ],
    "Espeon": [
        {location: "Route 4", method: "SOS Encounter", min_level: 11, max_level: 14, chance: 15},
        {location: "Route 6 — North", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
        {location: "Route 6 — South", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
    ],
    "Exeggcute": [
        {location: "Ancient Poni Path", method: "Walk", min_level: 40, max_level: 43, chance: 10},
        {location: "Exeggutor Island", method: "Walk", min_level: 40, max_level: 43, chance: 40},
        {location: "Poni Wilds", method: "Walk", min_level: 40, max_level: 43, chance: 10},
    ],
    "Fearow": [
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 40},
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 30},
        {location: "Poni Plains — North", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 70},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Route 10", method: "Bubbling Spots", min_level: 24, max_level: 27, chance: 80},
        {location: "Route 10", method: "Walk", min_level: 24, max_level: 27, chance: 30},
        {location: "Route 17 — Northeast", method: "Walk", min_level: 31, max_level: 34, chance: 30},
        {location: "Route 17 — West", method: "Walk", min_level: 31, max_level: 34, chance: 30},
    ],
    "Feebas": [
        {location: "Brooklet Hill — North", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 5},
        {location: "Brooklet Hill — North", method: "Super Rod", min_level: 10, max_level: 15, chance: 1},
        {location: "Brooklet Hill — South", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 5},
        {location: "Brooklet Hill — South", method: "Super Rod", min_level: 10, max_level: 15, chance: 1},
    ],
    "Finneon": [
        {location: "Brooklet Hill — Totems Den", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Hano Beach", method: "Surf", min_level: 21, max_level: 24, chance: 30},
        {location: "Kala’e Bay", method: "Surf", min_level: 15, max_level: 18, chance: 40},
        {location: "Melemele Sea", method: "Surf", min_level: 15, max_level: 18, chance: 40},
        {location: "Route 1 — Hauoli Outskirts", method: "Surf", min_level: 15, max_level: 18, chance: 40},
        {location: "Route 14", method: "Surf", min_level: 28, max_level: 31, chance: 40},
        {location: "Route 15 — Main", method: "Surf", min_level: 30, max_level: 33, chance: 40},
        {location: "Route 7", method: "Surf", min_level: 16, max_level: 19, chance: 30},
        {location: "Secluded Shore", method: "Surf", min_level: 27, max_level: 30, chance: 40},
    ],
    "Fletchinder": [
        {location: "Route 8 — Main", method: "Walk", min_level: 17, max_level: 20, chance: 15},
    ],
    "Fletchling": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 8},
        {location: "Wela Volcano Park", method: "Walk", min_level: 16, max_level: 19, chance: 30},
    ],
    "Fomantis": [
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 30},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Lush Jungle — West", method: "Bubbling Spots", min_level: 18, max_level: 21, chance: 100},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 20},
    ],
    "Gabite": [
        {location: "Haina Desert", method: "SOS (Bubbling Spot)", min_level: 28, max_level: 31, chance: 10},
        {location: "Haina Desert", method: "SOS Encounter", min_level: 28, max_level: 31, chance: 10},
    ],
    "Garbodor": [
        {location: "Malie City — Outer Cape", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 15},
    ],
    "Gastly": [
        {location: "Hau’oli Cemetery", method: "Walk", min_level: 7, max_level: 10, chance: 50},
        {location: "Memorial Hill", method: "Walk", min_level: 20, max_level: 23, chance: 50},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
    ],
    "Gastrodon": [
        {location: "Ancient Poni Path", method: "Walk", min_level: 40, max_level: 43, chance: 10},
        {location: "Exeggutor Island", method: "Walk", min_level: 40, max_level: 43, chance: 10},
        {location: "Poni Wilds", method: "Surf", min_level: 40, max_level: 43, chance: 20},
        {location: "Poni Wilds", method: "Walk", min_level: 40, max_level: 43, chance: 10},
    ],
    "Gengar": [
        {location: "Royal Avenue — Abandoned Site", method: "SOS Encounter", min_level: 29, max_level: 32, chance: 15},
    ],
    "Glalie": [
        {location: "Mount Lanakila — Cave", method: "SOS Encounter", min_level: 42, max_level: 45, chance: 15},
        {location: "Mount Lanakila — Outside", method: "SOS Encounter", min_level: 42, max_level: 45, chance: 15},
    ],
    "Golbat": [
        {location: "Mount Lanakila — Cave", method: "Walk", min_level: 42, max_level: 45, chance: 30},
        {location: "Resolution Cave", method: "Walk", min_level: 54, max_level: 57, chance: 70},
        {location: "Royal Avenue — Abandoned Site", method: "Walk", min_level: 29, max_level: 32, chance: 40},
        {location: "Vast Poni Canyon — Inside", method: "Walk", min_level: 41, max_level: 44, chance: 30},
        {location: "Vast Poni Canyon — Northwest", method: "Surf", min_level: 41, max_level: 44, chance: 80},
        {location: "Vast Poni Canyon — Northwest", method: "Walk", min_level: 41, max_level: 44, chance: 30},
    ],
    "Goldeen": [
        {location: "Brooklet Hill — North", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 45},
        {location: "Brooklet Hill — North", method: "Super Rod", min_level: 10, max_level: 15, chance: 29},
        {location: "Brooklet Hill — South", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 45},
        {location: "Brooklet Hill — South", method: "Super Rod", min_level: 10, max_level: 15, chance: 29},
        {location: "Malie Garden", method: "Super Rod", min_level: 10, max_level: 27, chance: 40},
    ],
    "Golduck": [
        {location: "Poni Gauntlet", method: "Walk", min_level: 56, max_level: 59, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "Surf", min_level: 41, max_level: 44, chance: 20},
    ],
    "Goomy": [
        {location: "Lush Jungle — North", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 10},
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 10},
        {location: "Lush Jungle — West", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 10},
        {location: "Route 17 — Northeast", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 10},
        {location: "Route 17 — West", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 10},
    ],
    "Gothita": [
        {location: "Route 6 — North", method: "Island Scan", min_level: 17, max_level: 17, chance: 100},
    ],
    "Granbull": [
        {location: "Ancient Poni Path", method: "Walk", min_level: 40, max_level: 43, chance: 20},
        {location: "Poni Gauntlet", method: "Walk", min_level: 56, max_level: 59, chance: 20},
        {location: "Poni Grove", method: "Walk", min_level: 52, max_level: 55, chance: 20},
        {location: "Poni Wilds", method: "Walk", min_level: 40, max_level: 43, chance: 20},
    ],
    "Graveler": [
        {location: "Tapu Village", method: "NPC Trade", min_level: 32, max_level: 32, chance: 100},
    ],
    "Growlithe": [
        {location: "Route 2 — North", method: "Walk", min_level: 7, max_level: 10, chance: 20},
    ],
    "Grubbin": [
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 10},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 10},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 10},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 10},
    ],
    "Gumshoos": [
        {location: "Akala Outskirts", method: "Walk", min_level: 20, max_level: 23, chance: 30},
        {location: "Ancient Poni Path", method: "Walk", min_level: 40, max_level: 43, chance: 30},
        {location: "Malie City — Outer Cape", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Poni Gauntlet", method: "Walk", min_level: 56, max_level: 59, chance: 30},
        {location: "Poni Grove", method: "Walk", min_level: 52, max_level: 55, chance: 30},
        {location: "Poni Plains — Center", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 70},
        {location: "Poni Plains — Center", method: "Walk", min_level: 54, max_level: 57, chance: 30},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 30},
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 30},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Wilds", method: "Walk", min_level: 40, max_level: 43, chance: 30},
        {location: "Route 10", method: "Walk", min_level: 24, max_level: 27, chance: 30},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 14", method: "Walk", min_level: 28, max_level: 31, chance: 30},
        {location: "Route 15 — Main", method: "Walk", min_level: 30, max_level: 33, chance: 30},
        {location: "Route 16 — Main", method: "Walk", min_level: 30, max_level: 33, chance: 30},
        {location: "Route 17 — Northeast", method: "Walk", min_level: 31, max_level: 34, chance: 30},
        {location: "Route 17 — West", method: "Walk", min_level: 31, max_level: 34, chance: 30},
        {location: "Tapu Village", method: "Walk", min_level: 28, max_level: 31, chance: 30},
    ],
    "Guzzlord": [
        {location: "Resolution Cave", method: "Static", min_level: 70, max_level: 70, chance: 100},
        {location: "Resolution Cave", method: "Walk", min_level: 70, max_level: 70, chance: 100},
    ],
    "Gyarados": [
        {location: "Brooklet Hill — North", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — North", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — South", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — South", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — Totems Den", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — Totems Den", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Kala’e Bay", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Kala’e Bay", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Malie Garden", method: "SOS Encounter", min_level: 10, max_level: 27, chance: 15},
        {location: "Melemele Sea", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 18, chance: 15},
        {location: "Melemele Sea", method: "SOS Encounter", min_level: 10, max_level: 18, chance: 15},
        {location: "Paniola Town", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 18, chance: 15},
        {location: "Paniola Town", method: "SOS Encounter", min_level: 10, max_level: 18, chance: 15},
        {location: "Poni Breaker Coast", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 43, chance: 15},
        {location: "Poni Breaker Coast", method: "SOS Encounter", min_level: 10, max_level: 43, chance: 15},
        {location: "Poni Gauntlet", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Gauntlet", method: "SOS Encounter", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Meadow", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 57, chance: 15},
        {location: "Poni Meadow", method: "SOS Encounter", min_level: 10, max_level: 57, chance: 15},
        {location: "Poni Wilds", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 43, chance: 15},
        {location: "Poni Wilds", method: "SOS Encounter", min_level: 10, max_level: 43, chance: 15},
        {location: "Route 13", method: "SOS Encounter", min_level: 10, max_level: 30, chance: 15},
        {location: "Route 14", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 31, chance: 15},
        {location: "Route 14", method: "SOS Encounter", min_level: 10, max_level: 31, chance: 15},
        {location: "Route 15 — Main", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 33, chance: 15},
        {location: "Route 15 — Main", method: "SOS Encounter", min_level: 10, max_level: 33, chance: 15},
        {location: "Route 7", method: "SOS Encounter", min_level: 10, max_level: 19, chance: 15},
        {location: "Route 8 — Main", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 25, chance: 15},
        {location: "Route 8 — Main", method: "SOS Encounter", min_level: 10, max_level: 20, chance: 15},
        {location: "Route 9 — Main", method: "SOS Encounter", min_level: 10, max_level: 23, chance: 15},
        {location: "Seafolk Village — Main", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 43, chance: 15},
        {location: "Seafolk Village — Main", method: "SOS Encounter", min_level: 10, max_level: 43, chance: 15},
        {location: "Seaward Cave", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Seaward Cave", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Secluded Shore", method: "SOS Encounter", min_level: 10, max_level: 30, chance: 15},
        {location: "Tapu Village", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 31, chance: 15},
        {location: "Tapu Village", method: "SOS Encounter", min_level: 10, max_level: 31, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 44, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS Encounter", min_level: 10, max_level: 44, chance: 15},
    ],
    "Hakamo-o": [
        {location: "Vast Poni Canyon — Outside", method: "SOS Encounter", min_level: 41, max_level: 44, chance: 15},
    ],
    "Happiny": [
        {location: "Hau'oli City — Shopping District", method: "SOS Encounter", min_level: 5, max_level: 8, chance: 15},
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Malie City — Main", method: "NPC Trade", min_level: 27, max_level: 27, chance: 100},
        {location: "Route 1 — South", method: "SOS Encounter", min_level: 10, max_level: 13, chance: 15},
        {location: "Route 1 — West", method: "SOS Encounter", min_level: 3, max_level: 5, chance: 15},
        {location: "Route 4", method: "SOS Encounter", min_level: 11, max_level: 14, chance: 15},
        {location: "Route 6 — North", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
        {location: "Route 6 — South", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
    ],
    "Hariyama": [
        {location: "Poni Plains — Center", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 30},
    ],
    "Haunter": [
        {location: "Royal Avenue — Abandoned Site", method: "Walk", min_level: 29, max_level: 32, chance: 40},
    ],
    "Honedge": [
        {location: "Akala Outskirts", method: "Island Scan", min_level: 23, max_level: 23, chance: 100},
    ],
    "Horsea": [
        {location: "Kala’e Bay", method: "Island Scan", min_level: 18, max_level: 18, chance: 100},
    ],
    "Hypno": [
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 20},
    ],
    "Igglybuff": [
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 10},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 10},
    ],
    "Jangmo-o": [
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 5},
    ],
    "Jigglypuff": [
        {location: "Route 4", method: "SOS Encounter", min_level: 11, max_level: 14, chance: 15},
        {location: "Route 6 — North", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
        {location: "Route 6 — South", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
    ],
    "Kadabra": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 3},
    ],
    "Kangaskhan": [
        {location: "Wela Volcano Park", method: "SOS Encounter", min_level: 16, max_level: 19, chance: 15},
        {location: "Wela Volcano Park", method: "Walk", min_level: 16, max_level: 19, chance: 1},
    ],
    "Kartana": [
        {location: "Malie Garden", method: "Static", min_level: 60, max_level: 60, chance: 100},
        {location: "Malie Garden", method: "Walk", min_level: 60, max_level: 60, chance: 100},
        {location: "Route 17 — All Areas", method: "Static", min_level: 60, max_level: 60, chance: 100},
        {location: "Route 17 — All Areas", method: "Walk", min_level: 60, max_level: 60, chance: 100},
    ],
    "Klefki": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 8},
        {location: "Royal Avenue — Abandoned Site", method: "Walk", min_level: 29, max_level: 32, chance: 15},
    ],
    "Klink": [
        {location: "Hau'oli City — Main", method: "Island Scan", min_level: 8, max_level: 8, chance: 100},
    ],
    "Komala": [
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 10},
    ],
    "Kommo-o": [
        {location: "Vast Poni Canyon — Outside", method: "SOS Encounter", min_level: 41, max_level: 44, chance: 15},
    ],
    "Lapras": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 7},
        {location: "Poni Wilds", method: "Surf", min_level: 40, max_level: 43, chance: 5},
    ],
    "Leavanny": [
        {location: "Poni Meadow", method: "Island Scan", min_level: 57, max_level: 57, chance: 100},
    ],
    "Ledian": [
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 10", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 17 — West", method: "Walk", min_level: 31, max_level: 34, chance: 20},
        {location: "Ula’ula Meadow", method: "Walk", min_level: 31, max_level: 34, chance: 20},
    ],
    "Ledyba": [
        {location: "Route 1 — East", method: "Walk", min_level: 2, max_level: 3, chance: 20},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 10},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 15},
    ],
    "Lillipup": [
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 20},
        {location: "Paniola Ranch", method: "Walk", min_level: 12, max_level: 15, chance: 40},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 30},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 30},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 30},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 30},
    ],
    "Litten": [
        {location: "Iki Town", method: "Gift", min_level: 5, max_level: 5, chance: 100},
    ],
    "Litwick": [
        {location: "Hau’oli Cemetery", method: "Island Scan", min_level: 10, max_level: 10, chance: 100},
    ],
    "Lucario": [
        {location: "Poni Grove", method: "SOS Encounter", min_level: 52, max_level: 55, chance: 15},
    ],
    "Lumineon": [
        {location: "Poni Wilds", method: "SOS Encounter", min_level: 40, max_level: 43, chance: 15},
        {location: "Poni Wilds", method: "Surf", min_level: 40, max_level: 43, chance: 25},
    ],
    "Lunala": [
        {location: "Altar of the Moone", method: "Static", min_level: 55, max_level: 55, chance: 100},
    ],
    "Luvdisc": [
        {location: "Melemele Sea", method: "Bubbling Spots", min_level: 10, max_level: 18, chance: 40},
        {location: "Melemele Sea", method: "Super Rod", min_level: 10, max_level: 18, chance: 1},
        {location: "Route 9 — Main", method: "Super Rod", min_level: 10, max_level: 23, chance: 70},
    ],
    "Luxio": [
        {location: "Route 8 — Main", method: "Island Scan", min_level: 20, max_level: 20, chance: 100},
    ],
    "Lycanroc Midday": [
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 20},
    ],
    "Machoke": [
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 30},
    ],
    "Machop": [
        {location: "Route 2 — Main", method: "NPC Trade", min_level: 9, max_level: 9, chance: 100},
        {location: "Ten Carat Hill — Farthest Hollow", method: "Walk", min_level: 10, max_level: 13, chance: 30},
    ],
    "Magby": [
        {location: "Wela Volcano Park", method: "Walk", min_level: 16, max_level: 19, chance: 15},
    ],
    "Magikarp": [
        {location: "Brooklet Hill — North", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 50},
        {location: "Brooklet Hill — North", method: "Super Rod", min_level: 10, max_level: 15, chance: 70},
        {location: "Brooklet Hill — South", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 50},
        {location: "Brooklet Hill — South", method: "Super Rod", min_level: 10, max_level: 15, chance: 70},
        {location: "Brooklet Hill — Totems Den", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 50},
        {location: "Brooklet Hill — Totems Den", method: "Super Rod", min_level: 10, max_level: 15, chance: 79},
        {location: "Kala’e Bay", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 50},
        {location: "Kala’e Bay", method: "Super Rod", min_level: 10, max_level: 15, chance: 79},
        {location: "Malie Garden", method: "Super Rod", min_level: 10, max_level: 27, chance: 60},
        {location: "Melemele Sea", method: "Bubbling Spots", min_level: 10, max_level: 18, chance: 20},
        {location: "Melemele Sea", method: "Super Rod", min_level: 10, max_level: 18, chance: 78},
        {location: "Paniola Town", method: "Bubbling Spots", min_level: 10, max_level: 18, chance: 50},
        {location: "Paniola Town", method: "Super Rod", min_level: 10, max_level: 18, chance: 99},
        {location: "Poni Breaker Coast", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 50},
        {location: "Poni Breaker Coast", method: "Super Rod", min_level: 10, max_level: 43, chance: 79},
        {location: "Poni Gauntlet", method: "Bubbling Spots", min_level: 10, max_level: 59, chance: 50},
        {location: "Poni Gauntlet", method: "Super Rod", min_level: 10, max_level: 59, chance: 59},
        {location: "Poni Meadow", method: "Bubbling Spots", min_level: 10, max_level: 57, chance: 50},
        {location: "Poni Meadow", method: "Super Rod", min_level: 10, max_level: 57, chance: 59},
        {location: "Poni Wilds", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 50},
        {location: "Poni Wilds", method: "Super Rod", min_level: 10, max_level: 43, chance: 79},
        {location: "Route 13", method: "Super Rod", min_level: 10, max_level: 30, chance: 79},
        {location: "Route 14", method: "Bubbling Spots", min_level: 10, max_level: 31, chance: 50},
        {location: "Route 14", method: "Super Rod", min_level: 10, max_level: 31, chance: 79},
        {location: "Route 15 — Main", method: "Bubbling Spots", min_level: 10, max_level: 33, chance: 50},
        {location: "Route 15 — Main", method: "Super Rod", min_level: 10, max_level: 33, chance: 79},
        {location: "Route 7", method: "Super Rod", min_level: 10, max_level: 19, chance: 79},
        {location: "Route 8 — Main", method: "Bubbling Spots", min_level: 10, max_level: 25, chance: 60},
        {location: "Route 8 — Main", method: "Super Rod", min_level: 10, max_level: 20, chance: 79},
        {location: "Route 9 — Main", method: "Super Rod", min_level: 10, max_level: 23, chance: 15},
        {location: "Seafolk Village — Main", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 50},
        {location: "Seafolk Village — Main", method: "Super Rod", min_level: 10, max_level: 43, chance: 79},
        {location: "Seaward Cave", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 50},
        {location: "Seaward Cave", method: "Super Rod", min_level: 10, max_level: 15, chance: 99},
        {location: "Secluded Shore", method: "Super Rod", min_level: 10, max_level: 30, chance: 79},
        {location: "Tapu Village", method: "Bubbling Spots", min_level: 10, max_level: 31, chance: 50},
        {location: "Tapu Village", method: "Super Rod", min_level: 10, max_level: 31, chance: 79},
        {location: "Vast Poni Canyon — Northwest", method: "Bubbling Spots", min_level: 10, max_level: 44, chance: 50},
        {location: "Vast Poni Canyon — Northwest", method: "Super Rod", min_level: 10, max_level: 44, chance: 59},
    ],
    "Magmar": [
        {location: "Wela Volcano Park", method: "SOS Encounter", min_level: 16, max_level: 19, chance: 15},
    ],
    "Magnemite": [
        {location: "Hau'oli City — Shopping District", method: "Walk", min_level: 5, max_level: 8, chance: 10},
        {location: "Malie City — Outer Cape", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
        {location: "Route 1 — Hauoli Outskirts", method: "Walk", min_level: 6, max_level: 8, chance: 50},
    ],
    "Makuhita": [
        {location: "Route 2 — North", method: "Bubbling Spots", min_level: 9, max_level: 10, chance: 30},
        {location: "Route 2 — South", method: "Bubbling Spots", min_level: 9, max_level: 10, chance: 30},
    ],
    "Mandibuzz": [
        {location: "Poni Plains — North", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 30},
    ],
    "Mankey": [
        {location: "Route 3 — North", method: "Walk", min_level: 9, max_level: 12, chance: 20},
        {location: "Route 3 — South", method: "Walk", min_level: 9, max_level: 12, chance: 20},
    ],
    "Mareanie": [
        {location: "Melemele Sea", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 18, chance: 15},
        {location: "Melemele Sea", method: "SOS Encounter", min_level: 10, max_level: 18, chance: 15},
        {location: "Route 9 — Main", method: "SOS Encounter", min_level: 10, max_level: 23, chance: 15},
    ],
    "Marill": [
        {location: "Brooklet Hill — Main", method: "Island Scan", min_level: 17, max_level: 17, chance: 100},
    ],
    "Masquerain": [
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 20},
    ],
    "Metang": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
    ],
    "Metapod": [
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 10},
        {location: "Melemele Meadow", method: "Walk", min_level: 9, max_level: 12, chance: 9},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 10},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 10},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 9},
    ],
    "Miltank": [
        {location: "Paniola Ranch", method: "SOS Encounter", min_level: 12, max_level: 15, chance: 15},
        {location: "Paniola Ranch", method: "Walk", min_level: 12, max_level: 15, chance: 5},
        {location: "Poni Plains — Center", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — Center", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — East", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — North", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — West", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 10},
    ],
    "Mimikyu Disguised": [
        {location: "Royal Avenue — Abandoned Site", method: "Walk", min_level: 29, max_level: 32, chance: 5},
    ],
    "Minior Red Meteor": [
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 30},
    ],
    "Misdreavus": [
        {location: "Hau’oli Cemetery", method: "Walk", min_level: 7, max_level: 10, chance: 30},
    ],
    "Mismagius": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
    ],
    "Morelull": [
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 20},
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 30},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 10},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 10},
    ],
    "Mudbray": [
        {location: "Blush Mountain", method: "Walk", min_level: 26, max_level: 29, chance: 20},
        {location: "Paniola Ranch", method: "Walk", min_level: 12, max_level: 15, chance: 50},
        {location: "Route 12", method: "Walk", min_level: 26, max_level: 29, chance: 30},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 20},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 20},
    ],
    "Mudsdale": [
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 20},
    ],
    "Munchlax": [
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 5},
    ],
    "Murkrow": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 3},
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 10},
    ],
    "Necrozma": [
        {location: "Ten Carat Hill — Farthest Hollow", method: "Walk", min_level: 75, max_level: 75, chance: 100},
    ],
    "Nihilego": [
        {location: "Diglett’s Tunnel", method: "Static", min_level: 55, max_level: 55, chance: 100},
        {location: "Diglett’s Tunnel", method: "Walk", min_level: 55, max_level: 55, chance: 100},
        {location: "Wela Volcano Park", method: "Static", min_level: 55, max_level: 55, chance: 100},
        {location: "Wela Volcano Park", method: "Walk", min_level: 55, max_level: 55, chance: 100},
    ],
    "Nosepass": [
        {location: "Akala Outskirts", method: "Walk", min_level: 20, max_level: 23, chance: 15},
    ],
    "Oranguru": [
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 5},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 5},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 5},
    ],
    "Oricorio Baile": [
        {location: "Ula’ula Meadow", method: "Walk", min_level: 31, max_level: 34, chance: 20},
    ],
    "Pancham": [
        {location: "Route 10", method: "Walk", min_level: 24, max_level: 27, chance: 10},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 17 — Northeast", method: "Walk", min_level: 31, max_level: 34, chance: 10},
        {location: "Route 17 — West", method: "Walk", min_level: 31, max_level: 34, chance: 20},
    ],
    "Pangoro": [
        {location: "Route 10", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 15},
        {location: "Route 11", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 15},
        {location: "Route 17 — Northeast", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 15},
        {location: "Route 17 — West", method: "SOS Encounter", min_level: 31, max_level: 34, chance: 15},
    ],
    "Paras": [
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 20},
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 30},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 10},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 10},
    ],
    "Passimian": [
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 5},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 5},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 5},
    ],
    "Pelipper": [
        {location: "Ancient Poni Path", method: "Walk", min_level: 40, max_level: 43, chance: 30},
        {location: "Exeggutor Island", method: "Walk", min_level: 40, max_level: 43, chance: 30},
        {location: "Poni Gauntlet", method: "Walk", min_level: 56, max_level: 59, chance: 30},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Wilds", method: "Surf", min_level: 40, max_level: 43, chance: 20},
        {location: "Poni Wilds", method: "Walk", min_level: 40, max_level: 43, chance: 30},
        {location: "Route 14", method: "Surf", min_level: 28, max_level: 31, chance: 20},
        {location: "Route 14", method: "Walk", min_level: 28, max_level: 31, chance: 30},
        {location: "Route 15 — Main", method: "Surf", min_level: 30, max_level: 33, chance: 20},
        {location: "Route 15 — Main", method: "Walk", min_level: 30, max_level: 33, chance: 50},
        {location: "Route 16 — Main", method: "Walk", min_level: 30, max_level: 33, chance: 50},
        {location: "Secluded Shore", method: "Surf", min_level: 27, max_level: 30, chance: 20},
        {location: "Tapu Village", method: "Walk", min_level: 28, max_level: 31, chance: 30},
    ],
    "Petilil": [
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 10},
        {location: "Melemele Meadow", method: "Walk", min_level: 9, max_level: 12, chance: 30},
        {location: "Poni Meadow", method: "Walk", min_level: 54, max_level: 57, chance: 50},
        {location: "Poni Plains — Center", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 70},
        {location: "Poni Plains — Center", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 20},
        {location: "Ula’ula Meadow", method: "Walk", min_level: 31, max_level: 34, chance: 30},
    ],
    "Phantump": [
        {location: "Memorial Hill", method: "Walk", min_level: 20, max_level: 23, chance: 30},
    ],
    "Pheromosa": [
        {location: "Verdant Cavern", method: "Static", min_level: 60, max_level: 60, chance: 100},
        {location: "Verdant Cavern — Trial Site", method: "Walk", min_level: 60, max_level: 60, chance: 100},
    ],
    "Pichu": [
        {location: "Hau'oli City — Shopping District", method: "Walk", min_level: 5, max_level: 8, chance: 5},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 5},
    ],
    "Pikachu": [
        {location: "Hau'oli City — Shopping District", method: "SOS Encounter", min_level: 5, max_level: 8, chance: 15},
        {location: "Route 1 — West", method: "SOS Encounter", min_level: 3, max_level: 5, chance: 15},
    ],
    "Pikipek": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
        {location: "Route 1 — East", method: "Walk", min_level: 2, max_level: 3, chance: 30},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 20},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 20},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 25},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 15},
        {location: "Route 5", method: "Walk", min_level: 13, max_level: 16, chance: 20},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 25},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 15},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 25},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 15},
        {location: "Route 8 — Main", method: "SOS Encounter", min_level: 17, max_level: 20, chance: 15},
    ],
    "Pinsir": [
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 10},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 8},
        {location: "Poni Grove", method: "Walk", min_level: 52, max_level: 55, chance: 10},
    ],
    "Politoed": [
        {location: "Malie Garden", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 1},
    ],
    "Poliwag": [
        {location: "Brooklet Hill — North", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Brooklet Hill — South", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Brooklet Hill — South", method: "Walk", min_level: 14, max_level: 17, chance: 20},
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 8},
    ],
    "Poliwhirl": [
        {location: "Konikoni City", method: "NPC Trade", min_level: 22, max_level: 22, chance: 100},
        {location: "Malie Garden", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 10},
    ],
    "Poliwrath": [
        {location: "Malie Garden", method: "SOS Encounter", min_level: 24, max_level: 27, chance: 1},
    ],
    "Popplio": [
        {location: "Iki Town", method: "Gift", min_level: 5, max_level: 5, chance: 100},
    ],
    "Porygon": [
        {location: "Route 15 — Aether House", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ],
    "Primeape": [
        {location: "Poni Plains — West", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 80},
    ],
    "Psyduck": [
        {location: "Brooklet Hill — North", method: "Surf", min_level: 14, max_level: 17, chance: 20},
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 30},
        {location: "Brooklet Hill — South", method: "Surf", min_level: 14, max_level: 17, chance: 20},
        {location: "Brooklet Hill — South", method: "Walk", min_level: 14, max_level: 17, chance: 30},
        {location: "Malie Garden", method: "Walk", min_level: 24, max_level: 27, chance: 10},
        {location: "Seaward Cave", method: "Surf", min_level: 15, max_level: 18, chance: 20},
    ],
    "Pyukumuku": [
        {location: "Hano Beach", method: "Surf", min_level: 21, max_level: 24, chance: 20},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 8},
        {location: "Route 7", method: "Surf", min_level: 16, max_level: 19, chance: 20},
    ],
    "Relicanth": [
        {location: "Poni Wilds", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 10},
        {location: "Poni Wilds", method: "Super Rod", min_level: 10, max_level: 43, chance: 1},
    ],
    "Rhyhorn": [
        {location: "Blush Mountain", method: "Island Scan", min_level: 30, max_level: 30, chance: 100},
    ],
    "Ribombee": [
        {location: "Poni Meadow", method: "Walk", min_level: 54, max_level: 57, chance: 30},
        {location: "Ula’ula Meadow", method: "Walk", min_level: 31, max_level: 34, chance: 30},
    ],
    "Riolu": [
        {location: "Poni Grove", method: "Walk", min_level: 52, max_level: 55, chance: 10},
    ],
    "Rockruff": [
        {location: "Ten Carat Hill — Farthest Hollow", method: "Walk", min_level: 10, max_level: 13, chance: 20},
    ],
    "Roggenrola": [
        {location: "Ten Carat Hill — Farthest Hollow", method: "Walk", min_level: 10, max_level: 13, chance: 20},
        {location: "Ten Carat Hill — Inside", method: "Walk", min_level: 10, max_level: 13, chance: 30},
    ],
    "Roselia": [
        {location: "Ula’ula Meadow", method: "Island Scan", min_level: 34, max_level: 34, chance: 100},
    ],
    "Rowlet": [
        {location: "Iki Town", method: "Gift", min_level: 5, max_level: 5, chance: 100},
    ],
    "Rufflet": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 3},
        {location: "Route 3 — North", method: "Bubbling Spots", min_level: 11, max_level: 12, chance: 30},
    ],
    "Sableye": [
        {location: "Ten Carat Hill — Inside", method: "SOS Encounter", min_level: 10, max_level: 13, chance: 15},
        {location: "Vast Poni Canyon — Inside", method: "SOS Encounter", min_level: 41, max_level: 44, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS Encounter", min_level: 41, max_level: 44, chance: 15},
    ],
    "Salamence": [
        {location: "Route 3 — South", method: "SOS Encounter", min_level: 9, max_level: 12, chance: 15},
    ],
    "Salandit": [
        {location: "Route 8 — Main", method: "Walk", min_level: 17, max_level: 20, chance: 20},
        {location: "Wela Volcano Park", method: "Walk", min_level: 16, max_level: 19, chance: 30},
    ],
    "Samurott": [
        {location: "Poni Wilds", method: "Island Scan", min_level: 43, max_level: 43, chance: 100},
    ],
    "Sandile": [
        {location: "Haina Desert", method: "Bubbling Spots", min_level: 28, max_level: 31, chance: 70},
        {location: "Haina Desert", method: "Walk", min_level: 28, max_level: 31, chance: 70},
    ],
    "Sandygast": [
        {location: "Hano Beach", method: "Walk", min_level: 21, max_level: 24, chance: 20},
    ],
    "Scyther": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 7},
        {location: "Poni Plains — Center", method: "Bubbling Spots", min_level: 54, max_level: 57, chance: 30},
    ],
    "Seaking": [
        {location: "Brooklet Hill — North", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — North", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — South", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Brooklet Hill — South", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Malie Garden", method: "SOS Encounter", min_level: 10, max_level: 27, chance: 15},
    ],
    "Serperior": [
        {location: "Exeggutor Island", method: "Island Scan", min_level: 43, max_level: 43, chance: 100},
    ],
    "Sharpedo": [
        {location: "Poni Breaker Coast", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 10},
        {location: "Poni Breaker Coast", method: "Super Rod", min_level: 10, max_level: 43, chance: 1},
    ],
    "Shelgon": [
        {location: "Kala’e Bay", method: "SOS Encounter", min_level: 15, max_level: 18, chance: 15},
    ],
    "Shellder": [
        {location: "Kala’e Bay", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 20},
        {location: "Kala’e Bay", method: "Super Rod", min_level: 10, max_level: 15, chance: 1},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
    ],
    "Shieldon": [
        {location: "Route 8 — Fossil Restoration Center", method: "Gift", min_level: 15, max_level: 15, chance: 100},
    ],
    "Skarmory": [
        {location: "Mount Hokulani — Main", method: "Walk", min_level: 25, max_level: 28, chance: 10},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 8},
        {location: "Route 10", method: "Bubbling Spots", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 10", method: "Walk", min_level: 24, max_level: 27, chance: 10},
        {location: "Route 17 — Northeast", method: "Walk", min_level: 31, max_level: 34, chance: 10},
        {location: "Vast Poni Canyon — Outside", method: "Walk", min_level: 41, max_level: 44, chance: 10},
    ],
    "Sliggoo": [
        {location: "Exeggutor Island", method: "SOS Encounter", min_level: 40, max_level: 43, chance: 10},
    ],
    "Slowbro": [
        {location: "Kala’e Bay", method: "SOS Encounter", min_level: 15, max_level: 18, chance: 15},
    ],
    "Slowpoke": [
        {location: "Kala’e Bay", method: "Walk", min_level: 15, max_level: 18, chance: 20},
        {location: "Route 1 — Hauoli Outskirts", method: "Walk", min_level: 5, max_level: 7, chance: 20},
        {location: "Route 15 — Main", method: "Walk", min_level: 30, max_level: 33, chance: 20},
        {location: "Route 16 — Main", method: "Walk", min_level: 30, max_level: 33, chance: 20},
    ],
    "Smeargle": [
        {location: "Route 2 — North", method: "Walk", min_level: 7, max_level: 10, chance: 10},
        {location: "Route 2 — South", method: "Walk", min_level: 7, max_level: 10, chance: 20},
    ],
    "Sneasel": [
        {location: "Mount Lanakila — Cave", method: "Walk", min_level: 42, max_level: 45, chance: 20},
        {location: "Mount Lanakila — Outside", method: "Walk", min_level: 42, max_level: 45, chance: 20},
    ],
    "Snorlax": [
        {location: "Route 1 — South", method: "SOS Encounter", min_level: 10, max_level: 13, chance: 15},
    ],
    "Snorunt": [
        {location: "Mount Lanakila — Cave", method: "Walk", min_level: 42, max_level: 45, chance: 30},
        {location: "Mount Lanakila — Outside", method: "Walk", min_level: 42, max_level: 45, chance: 30},
        {location: "Route 14", method: "Walk", min_level: 28, max_level: 31, chance: 20},
        {location: "Tapu Village", method: "Walk", min_level: 28, max_level: 31, chance: 20},
    ],
    "Solgaleo": [
        {location: "Altar of the Sunne", method: "Static", min_level: 55, max_level: 55, chance: 100},
    ],
    "Spearow": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
        {location: "Route 2 — North", method: "Walk", min_level: 7, max_level: 10, chance: 40},
        {location: "Route 3 — North", method: "Bubbling Spots", min_level: 11, max_level: 12, chance: 70},
        {location: "Route 3 — North", method: "Walk", min_level: 9, max_level: 12, chance: 40},
        {location: "Route 3 — South", method: "Walk", min_level: 9, max_level: 12, chance: 49},
    ],
    "Spheal": [
        {location: "Route 7", method: "Island Scan", min_level: 19, max_level: 19, chance: 100},
    ],
    "Spinarak": [
        {location: "Route 1 — East", method: "Walk", min_level: 2, max_level: 3, chance: 20},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 10},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 15},
    ],
    "Spinda": [
        {location: "Ten Carat Hill — Farthest Hollow", method: "Walk", min_level: 10, max_level: 13, chance: 10},
    ],
    "Staravia": [
        {location: "Route 10", method: "Island Scan", min_level: 27, max_level: 27, chance: 100},
    ],
    "Starmie": [
        {location: "Route 7", method: "SOS Encounter", min_level: 10, max_level: 19, chance: 15},
    ],
    "Staryu": [
        {location: "Hano Beach", method: "Walk", min_level: 21, max_level: 24, chance: 80},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 8},
        {location: "Route 7", method: "Super Rod", min_level: 10, max_level: 19, chance: 1},
    ],
    "Steenee": [
        {location: "Seafolk Village — Main", method: "NPC Trade", min_level: 43, max_level: 43, chance: 100},
    ],
    "Stufful": [
        {location: "Akala Outskirts", method: "Walk", min_level: 20, max_level: 23, chance: 5},
        {location: "Route 8 — Main", method: "Walk", min_level: 17, max_level: 20, chance: 5},
    ],
    "Sudowoodo": [
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Route 1 — South", method: "SOS Encounter", min_level: 10, max_level: 13, chance: 15},
    ],
    "Surskit": [
        {location: "Brooklet Hill — North", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Brooklet Hill — South", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Brooklet Hill — South", method: "Walk", min_level: 14, max_level: 17, chance: 20},
    ],
    "Swinub": [
        {location: "Tapu Village", method: "Island Scan", min_level: 31, max_level: 31, chance: 100},
    ],
    "Talonflame": [
        {location: "Poni Gauntlet", method: "NPC Trade", min_level: 59, max_level: 59, chance: 100},
    ],
    "Tapu Bulu": [
        {location: "Ruins of Abundance", method: "Static", min_level: 60, max_level: 60, chance: 100},
    ],
    "Tapu Fini": [
        {location: "Ruins of Hope", method: "Static", min_level: 60, max_level: 60, chance: 100},
    ],
    "Tapu Koko": [
        {location: "Ruins of Conflict", method: "Static", min_level: 60, max_level: 60, chance: 100},
    ],
    "Tapu Lele": [
        {location: "Ruins of Life", method: "Static", min_level: 60, max_level: 60, chance: 100},
    ],
    "Tauros": [
        {location: "Paniola Ranch", method: "SOS Encounter", min_level: 12, max_level: 15, chance: 15},
        {location: "Paniola Ranch", method: "Walk", min_level: 12, max_level: 15, chance: 5},
        {location: "Poni Plains — Center", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — Center", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — East", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — North", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — West", method: "SOS Encounter", min_level: 54, max_level: 57, chance: 15},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 10},
    ],
    "Tentacool": [
        {location: "Brooklet Hill — Totems Den", method: "Surf", min_level: 14, max_level: 17, chance: 40},
        {location: "Hano Beach", method: "Bubbling Spots", min_level: 21, max_level: 24, chance: 100},
        {location: "Hano Beach", method: "Surf", min_level: 21, max_level: 24, chance: 30},
        {location: "Kala’e Bay", method: "Surf", min_level: 15, max_level: 18, chance: 40},
        {location: "Melemele Sea", method: "Surf", min_level: 15, max_level: 18, chance: 40},
        {location: "Route 1 — Hauoli Outskirts", method: "Surf", min_level: 15, max_level: 18, chance: 40},
        {location: "Route 14", method: "Surf", min_level: 28, max_level: 31, chance: 40},
        {location: "Route 15 — Main", method: "Surf", min_level: 30, max_level: 33, chance: 40},
        {location: "Route 7", method: "Surf", min_level: 16, max_level: 19, chance: 30},
        {location: "Secluded Shore", method: "Surf", min_level: 27, max_level: 30, chance: 40},
    ],
    "Tentacruel": [
        {location: "Poni Wilds", method: "Surf", min_level: 40, max_level: 43, chance: 30},
    ],
    "Tirtouga": [
        {location: "Route 8 — Fossil Restoration Center", method: "Gift", min_level: 15, max_level: 15, chance: 100},
    ],
    "Togedemaru": [
        {location: "Blush Mountain", method: "Walk", min_level: 26, max_level: 29, chance: 10},
    ],
    "Togekiss": [
        {location: "Poni Gauntlet", method: "Island Scan", min_level: 59, max_level: 59, chance: 100},
    ],
    "Torkoal": [
        {location: "Blush Mountain", method: "Walk", min_level: 26, max_level: 29, chance: 20},
        {location: "Route 12", method: "Walk", min_level: 26, max_level: 29, chance: 20},
    ],
    "Totodile": [
        {location: "Seaward Cave", method: "Island Scan", min_level: 12, max_level: 12, chance: 100},
    ],
    "Trapinch": [
        {location: "Haina Desert", method: "Bubbling Spots", min_level: 28, max_level: 31, chance: 10},
    ],
    "Trevenant": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 3},
    ],
    "Trubbish": [
        {location: "Malie City — Outer Cape", method: "Walk", min_level: 24, max_level: 27, chance: 30},
    ],
    "Trumbeak": [
        {location: "Lush Jungle — North", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Lush Jungle — North", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Lush Jungle — South", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Lush Jungle — South", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Lush Jungle — West", method: "SOS Encounter", min_level: 18, max_level: 21, chance: 15},
        {location: "Lush Jungle — West", method: "Walk", min_level: 18, max_level: 21, chance: 20},
        {location: "Poni Grove", method: "Walk", min_level: 52, max_level: 55, chance: 30},
        {location: "Poni Plains — Center", method: "Walk", min_level: 54, max_level: 57, chance: 30},
        {location: "Poni Plains — East", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — North", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Poni Plains — West", method: "Walk", min_level: 54, max_level: 57, chance: 10},
        {location: "Route 11", method: "Walk", min_level: 24, max_level: 27, chance: 20},
        {location: "Route 8 — Main", method: "Walk", min_level: 17, max_level: 20, chance: 30},
    ],
    "Turtonator": [
        {location: "Blush Mountain", method: "Walk", min_level: 26, max_level: 29, chance: 10},
    ],
    "Type: Null": [
        {location: "Aether Paradise — 2f", method: "Gift", min_level: 40, max_level: 40, chance: 100},
    ],
    "Umbreon": [
        {location: "Route 4", method: "SOS Encounter", min_level: 11, max_level: 14, chance: 15},
        {location: "Route 6 — North", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
        {location: "Route 6 — South", method: "SOS Encounter", min_level: 14, max_level: 17, chance: 15},
    ],
    "Vanillish": [
        {location: "Mount Lanakila — Outside", method: "SOS Encounter", min_level: 42, max_level: 45, chance: 10},
    ],
    "Vanillite": [
        {location: "Tapu Village", method: "SOS Encounter", min_level: 28, max_level: 31, chance: 10},
    ],
    "Venipede": [
        {location: "Route 4", method: "Island Scan", min_level: 14, max_level: 14, chance: 100},
    ],
    "Vigoroth": [
        {location: "Route 11", method: "Island Scan", min_level: 27, max_level: 27, chance: 100},
    ],
    "Voltorb": [
        {location: "New Mauville", method: "Static", min_level: 25, max_level: 25, chance: 100},
    ],
    "Vullaby": [
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 2},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 3},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 3},
        {location: "Route 3 — North", method: "Bubbling Spots", min_level: 11, max_level: 12, chance: 30},
    ],
    "Wailmer": [
        {location: "Poni Breaker Coast", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 40},
        {location: "Poni Breaker Coast", method: "Super Rod", min_level: 10, max_level: 43, chance: 20},
        {location: "Poni Wilds", method: "Bubbling Spots", min_level: 40, max_level: 43, chance: 90},
        {location: "Poni Wilds", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 40},
        {location: "Poni Wilds", method: "Super Rod", min_level: 10, max_level: 43, chance: 20},
        {location: "Seafolk Village — Main", method: "Bubbling Spots", min_level: 10, max_level: 43, chance: 40},
        {location: "Seafolk Village — Main", method: "Super Rod", min_level: 10, max_level: 43, chance: 20},
    ],
    "Wailord": [
        {location: "Poni Breaker Coast", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 43, chance: 15},
        {location: "Poni Breaker Coast", method: "SOS Encounter", min_level: 10, max_level: 43, chance: 15},
        {location: "Poni Wilds", method: "Bubbling Spots", min_level: 40, max_level: 43, chance: 10},
        {location: "Poni Wilds", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 43, chance: 15},
        {location: "Poni Wilds", method: "SOS Encounter", min_level: 10, max_level: 43, chance: 15},
        {location: "Seafolk Village — Main", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 43, chance: 15},
        {location: "Seafolk Village — Main", method: "SOS Encounter", min_level: 10, max_level: 43, chance: 15},
    ],
    "Whiscash": [
        {location: "Paniola Town", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 18, chance: 15},
        {location: "Paniola Town", method: "SOS Encounter", min_level: 10, max_level: 18, chance: 15},
        {location: "Poni Gauntlet", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Gauntlet", method: "SOS Encounter", min_level: 10, max_level: 59, chance: 15},
        {location: "Poni Meadow", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 57, chance: 15},
        {location: "Poni Meadow", method: "SOS Encounter", min_level: 10, max_level: 57, chance: 15},
        {location: "Seaward Cave", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 15, chance: 15},
        {location: "Seaward Cave", method: "SOS Encounter", min_level: 10, max_level: 15, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS (Bubbling Spot)", min_level: 10, max_level: 44, chance: 15},
        {location: "Vast Poni Canyon — Northwest", method: "SOS Encounter", min_level: 10, max_level: 44, chance: 15},
    ],
    "Wimpod": [
        {location: "Poni Breaker Coast", method: "Static", min_level: 40, max_level: 43, chance: 100},
        {location: "Poni Wilds", method: "Static", min_level: 40, max_level: 43, chance: 100},
        {location: "Route 8 — Main", method: "Static", min_level: 17, max_level: 20, chance: 100},
    ],
    "Wingull": [
        {location: "Akala Outskirts", method: "Walk", min_level: 20, max_level: 23, chance: 50},
        {location: "Brooklet Hill — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Brooklet Hill — South", method: "Walk", min_level: 14, max_level: 17, chance: 30},
        {location: "Brooklet Hill — Totems Den", method: "Surf", min_level: 14, max_level: 17, chance: 20},
        {location: "Hano Beach", method: "Surf", min_level: 21, max_level: 24, chance: 20},
        {location: "Hau'oli City — Shopping District", method: "Walk", min_level: 5, max_level: 8, chance: 20},
        {location: "Kala’e Bay", method: "Surf", min_level: 15, max_level: 18, chance: 20},
        {location: "Kala’e Bay", method: "Walk", min_level: 15, max_level: 18, chance: 40},
        {location: "Melemele Sea", method: "Surf", min_level: 15, max_level: 18, chance: 20},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
        {location: "Route 1 — Hauoli Outskirts", method: "Surf", min_level: 15, max_level: 18, chance: 20},
        {location: "Route 1 — Hauoli Outskirts", method: "Walk", min_level: 5, max_level: 7, chance: 50},
        {location: "Route 7", method: "Surf", min_level: 16, max_level: 19, chance: 20},
    ],
    "Wishiwashi Solo": [
        {location: "Brooklet Hill — Totems Den", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 30},
        {location: "Brooklet Hill — Totems Den", method: "Super Rod", min_level: 10, max_level: 15, chance: 20},
        {location: "Kala’e Bay", method: "Bubbling Spots", min_level: 10, max_level: 15, chance: 30},
        {location: "Kala’e Bay", method: "Super Rod", min_level: 10, max_level: 15, chance: 20},
        {location: "Melemele Sea", method: "Bubbling Spots", min_level: 10, max_level: 18, chance: 20},
        {location: "Melemele Sea", method: "Super Rod", min_level: 10, max_level: 18, chance: 20},
        {location: "Route 13", method: "Super Rod", min_level: 10, max_level: 30, chance: 20},
        {location: "Route 14", method: "Bubbling Spots", min_level: 10, max_level: 31, chance: 30},
        {location: "Route 14", method: "Super Rod", min_level: 10, max_level: 31, chance: 20},
        {location: "Route 15 — Main", method: "Bubbling Spots", min_level: 10, max_level: 33, chance: 30},
        {location: "Route 15 — Main", method: "Super Rod", min_level: 10, max_level: 33, chance: 20},
        {location: "Route 7", method: "Super Rod", min_level: 10, max_level: 19, chance: 20},
        {location: "Route 8 — Main", method: "Bubbling Spots", min_level: 10, max_level: 25, chance: 20},
        {location: "Route 8 — Main", method: "Super Rod", min_level: 10, max_level: 20, chance: 20},
        {location: "Route 9 — Main", method: "Super Rod", min_level: 10, max_level: 23, chance: 10},
        {location: "Secluded Shore", method: "Super Rod", min_level: 10, max_level: 30, chance: 20},
        {location: "Tapu Village", method: "Bubbling Spots", min_level: 10, max_level: 31, chance: 30},
        {location: "Tapu Village", method: "Super Rod", min_level: 10, max_level: 31, chance: 20},
    ],
    "Xurkitree": [
        {location: "Lush Jungle — All Areas", method: "Static", min_level: 65, max_level: 65, chance: 100},
        {location: "Lush Jungle — All Areas", method: "Walk", min_level: 65, max_level: 65, chance: 100},
        {location: "Memorial Hill", method: "Static", min_level: 65, max_level: 65, chance: 100},
        {location: "Memorial Hill", method: "Walk", min_level: 65, max_level: 65, chance: 100},
    ],
    "Yungoos": [
        {location: "Hau'oli City — Shopping District", method: "Walk", min_level: 5, max_level: 8, chance: 20},
        {location: "Kala’e Bay", method: "Walk", min_level: 15, max_level: 18, chance: 30},
        {location: "Route 1 — East", method: "Walk", min_level: 2, max_level: 3, chance: 30},
        {location: "Route 1 — Hauoli Outskirts", method: "Walk", min_level: 5, max_level: 7, chance: 30},
        {location: "Route 1 — South", method: "Walk", min_level: 10, max_level: 13, chance: 30},
        {location: "Route 1 — West", method: "Walk", min_level: 3, max_level: 5, chance: 30},
        {location: "Route 2 — North", method: "Bubbling Spots", min_level: 9, max_level: 10, chance: 70},
        {location: "Route 2 — North", method: "Walk", min_level: 7, max_level: 10, chance: 10},
        {location: "Route 2 — South", method: "Bubbling Spots", min_level: 9, max_level: 10, chance: 70},
        {location: "Route 2 — South", method: "Walk", min_level: 7, max_level: 10, chance: 10},
        {location: "Route 3 — North", method: "Walk", min_level: 9, max_level: 12, chance: 10},
        {location: "Route 3 — South", method: "Walk", min_level: 9, max_level: 12, chance: 10},
        {location: "Route 4", method: "Walk", min_level: 11, max_level: 14, chance: 10},
        {location: "Route 6 — North", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Route 6 — South", method: "Walk", min_level: 14, max_level: 17, chance: 10},
        {location: "Route 8 — Main", method: "Walk", min_level: 17, max_level: 20, chance: 30},
    ],
    "Zubat": [
        {location: "Diglett’s Tunnel", method: "Walk", min_level: 19, max_level: 22, chance: 70},
        {location: "Hau’oli Cemetery", method: "Walk", min_level: 7, max_level: 10, chance: 20},
        {location: "Lush Jungle — East Cave", method: "Walk", min_level: 18, max_level: 21, chance: 70},
        {location: "Memorial Hill", method: "Walk", min_level: 20, max_level: 23, chance: 20},
        {location: "Poké Pelago — Elite Four Defeated", method: "Gift", min_level: 49, max_level: 55, chance: 4},
        {location: "Poké Pelago — Poni Island Reached", method: "Gift", min_level: 37, max_level: 43, chance: 5},
        {location: "Poké Pelago — Ulaula Island Reached", method: "Gift", min_level: 21, max_level: 27, chance: 6},
        {location: "Seaward Cave", method: "Surf", min_level: 15, max_level: 18, chance: 80},
        {location: "Seaward Cave", method: "Walk", min_level: 9, max_level: 12, chance: 70},
        {location: "Ten Carat Hill — Inside", method: "Walk", min_level: 10, max_level: 13, chance: 30},
        {location: "Verdant Cavern — Trial Site", method: "Walk", min_level: 8, max_level: 11, chance: 70},
    ],
    "Zygarde 50": [
        {location: "Route 16 — Main", method: "Gift", min_level: 50, max_level: 50, chance: 100},
        {location: "Route 16 — Main", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ]
};
