export const encounters_by_pokemon = {
    "Abra": [
        {location: "Road 5", method: "Walk", min_level: 7, max_level: 7, chance: 15},
        {location: "Road 6", method: "Walk", min_level: 7, max_level: 7, chance: 15},
        {location: "Road 7", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 7", method: "Walk", min_level: 19, max_level: 19, chance: 10},
        {location: "Road 7", method: "Walk", min_level: 26, max_level: 26, chance: 5},
        {location: "Road 8", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 8", method: "Walk", min_level: 19, max_level: 19, chance: 10},
    ],
    "Aerodactyl": [
        {location: "Cinnabar Lab (Cinnabar Island)", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ],
    "Articuno": [
        {location: "Seafoam Islands (B4F)", method: "Static", min_level: 50, max_level: 50, chance: 100},
    ],
    "Bellsprout": [
        {location: "Road 12", method: "Walk", min_level: 25, max_level: 25, chance: 20},
        {location: "Road 12", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Road 13", method: "Walk", min_level: 25, max_level: 25, chance: 20},
        {location: "Road 13", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Road 14", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Road 14", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 15", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Road 15", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 24", method: "Walk", min_level: 12, max_level: 12, chance: 20},
        {location: "Road 24", method: "Walk", min_level: 14, max_level: 14, chance: 10},
        {location: "Road 25", method: "Walk", min_level: 12, max_level: 12, chance: 20},
        {location: "Road 25", method: "Walk", min_level: 14, max_level: 14, chance: 10},
    ],
    "Bulbasaur": [
        {location: "Cerulean City", method: "Gift", min_level: 10, max_level: 10, chance: 100},
    ],
    "Caterpie": [
        {location: "Viridian Forest", method: "Walk", min_level: 3, max_level: 3, chance: 20},
        {location: "Viridian Forest", method: "Walk", min_level: 4, max_level: 4, chance: 15},
        {location: "Viridian Forest", method: "Walk", min_level: 5, max_level: 5, chance: 10},
        {location: "Viridian Forest", method: "Walk", min_level: 6, max_level: 6, chance: 5},
    ],
    "Chansey": [
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 56, max_level: 56, chance: 5},
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 21, max_level: 21, chance: 4},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 7, max_level: 7, chance: 1},
    ],
    "Charmander": [
        {location: "Road 24", method: "Gift", min_level: 10, max_level: 10, chance: 100},
    ],
    "Clefairy": [
        {location: "Mount Moon (1F)", method: "Walk", min_level: 11, max_level: 11, chance: 1},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 10, max_level: 10, chance: 4},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 12, max_level: 12, chance: 1},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 9, max_level: 9, chance: 5},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 11, max_level: 11, chance: 4},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 13, max_level: 13, chance: 1},
    ],
    "Cubone": [
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 20, max_level: 20, chance: 5},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 22, max_level: 22, chance: 5},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 24, max_level: 24, chance: 5},
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 19, max_level: 19, chance: 10},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 16, max_level: 16, chance: 5},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 19, max_level: 19, chance: 10},
    ],
    "Dewgong": [
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 28, max_level: 28, chance: 4},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 32, max_level: 32, chance: 1},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 30, max_level: 30, chance: 4},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 34, max_level: 34, chance: 1},
    ],
    "Diglett": [
        {location: "Digletts Cave", method: "Walk", min_level: 18, max_level: 18, chance: 20},
        {location: "Digletts Cave", method: "Walk", min_level: 19, max_level: 19, chance: 20},
        {location: "Digletts Cave", method: "Walk", min_level: 17, max_level: 17, chance: 15},
        {location: "Digletts Cave", method: "Walk", min_level: 20, max_level: 20, chance: 10},
        {location: "Digletts Cave", method: "Walk", min_level: 16, max_level: 16, chance: 10},
        {location: "Digletts Cave", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Digletts Cave", method: "Walk", min_level: 21, max_level: 21, chance: 5},
        {location: "Digletts Cave", method: "Walk", min_level: 22, max_level: 22, chance: 5},
    ],
    "Ditto": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 55, max_level: 55, chance: 4},
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 60, max_level: 60, chance: 1},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 60, max_level: 60, chance: 10},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 60, max_level: 60, chance: 10},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 65, max_level: 65, chance: 5},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 24, max_level: 24, chance: 5},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 18, max_level: 18, chance: 4},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 12, max_level: 12, chance: 1},
    ],
    "Dodrio": [
        {location: "Road 17", method: "Walk", min_level: 29, max_level: 29, chance: 1},
    ],
    "Doduo": [
        {location: "Road 16", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Road 16", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Road 16", method: "Walk", min_level: 26, max_level: 26, chance: 10},
        {location: "Road 17", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Road 17", method: "Walk", min_level: 27, max_level: 27, chance: 15},
        {location: "Road 17", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 17", method: "Walk", min_level: 28, max_level: 28, chance: 5},
        {location: "Road 18", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Road 18", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Road 18", method: "Walk", min_level: 26, max_level: 26, chance: 10},
    ],
    "Dragonair": [
        {location: "Safari Zone (middle)", method: "Super Rod", min_level: 15, max_level: 15, chance: 10},
    ],
    "Dratini": [
        {location: "Safari Zone (Area 1, east)", method: "Super Rod", min_level: 15, max_level: 15, chance: 10},
        {location: "Safari Zone (Area 2, north)", method: "Super Rod", min_level: 15, max_level: 15, chance: 10},
        {location: "Safari Zone (Area 3, west)", method: "Super Rod", min_level: 15, max_level: 15, chance: 10},
        {location: "Safari Zone (middle)", method: "Super Rod", min_level: 10, max_level: 10, chance: 20},
    ],
    "Drowzee": [
        {location: "Road 11", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 11", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 11", method: "Walk", min_level: 19, max_level: 19, chance: 4},
    ],
    "Dugtrio": [
        {location: "Digletts Cave", method: "Walk", min_level: 29, max_level: 29, chance: 4},
        {location: "Digletts Cave", method: "Walk", min_level: 31, max_level: 31, chance: 1},
    ],
    "Eevee": [
        {location: "Celadon Mansion rooftop", method: "Gift", min_level: 25, max_level: 25, chance: 100},
    ],
    "Electrode": [
        {location: "Power Plant", method: "Static", min_level: 43, max_level: 43, chance: 100},
    ],
    "Exeggcute": [
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 22, max_level: 22, chance: 15},
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 26, max_level: 26, chance: 5},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 20, max_level: 20, chance: 15},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 22, max_level: 22, chance: 15},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 26, max_level: 26, chance: 5},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 24, max_level: 24, chance: 15},
    ],
    "Farfetch'd": [
        {location: "Road 12", method: "Walk", min_level: 26, max_level: 26, chance: 4},
        {location: "Road 12", method: "Walk", min_level: 31, max_level: 31, chance: 1},
        {location: "Road 13", method: "Walk", min_level: 26, max_level: 26, chance: 4},
        {location: "Road 13", method: "Walk", min_level: 31, max_level: 31, chance: 1},
    ],
    "Fearow": [
        {location: "Road 16", method: "Walk", min_level: 24, max_level: 24, chance: 5},
        {location: "Road 17", method: "Walk", min_level: 27, max_level: 27, chance: 20},
        {location: "Road 17", method: "Walk", min_level: 29, max_level: 29, chance: 5},
        {location: "Road 18", method: "Walk", min_level: 24, max_level: 24, chance: 5},
        {location: "Road 23", method: "Walk", min_level: 40, max_level: 40, chance: 10},
        {location: "Road 23", method: "Walk", min_level: 45, max_level: 45, chance: 5},
        {location: "Road 9", method: "Walk", min_level: 19, max_level: 19, chance: 1},
    ],
    "Gastly": [
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 20, max_level: 20, chance: 20},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 21, max_level: 21, chance: 20},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 22, max_level: 22, chance: 15},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 23, max_level: 23, chance: 10},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 19, max_level: 19, chance: 10},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 18, max_level: 18, chance: 5},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 25, max_level: 25, chance: 5},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 20, max_level: 20, chance: 20},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 21, max_level: 21, chance: 20},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 22, max_level: 22, chance: 15},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 23, max_level: 23, chance: 10},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 19, max_level: 19, chance: 10},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 18, max_level: 18, chance: 5},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 25, max_level: 25, chance: 5},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 23, max_level: 23, chance: 20},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 24, max_level: 24, chance: 15},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 25, max_level: 25, chance: 10},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 26, max_level: 26, chance: 10},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 21, max_level: 21, chance: 10},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 27, max_level: 27, chance: 5},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 23, max_level: 23, chance: 20},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 24, max_level: 24, chance: 15},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 25, max_level: 25, chance: 10},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 26, max_level: 26, chance: 10},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 21, max_level: 21, chance: 10},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 27, max_level: 27, chance: 5},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 24, max_level: 24, chance: 20},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 25, max_level: 25, chance: 20},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 26, max_level: 26, chance: 15},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 23, max_level: 23, chance: 10},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 29, max_level: 29, chance: 5},
    ],
    "Geodude": [
        {location: "Mount Moon (1F)", method: "Walk", min_level: 10, max_level: 10, chance: 15},
        {location: "Mount Moon (1F)", method: "Walk", min_level: 10, max_level: 10, chance: 5},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 10, max_level: 10, chance: 10},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 11, max_level: 11, chance: 10},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 11, max_level: 11, chance: 20},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 16, max_level: 16, chance: 20},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 18, max_level: 18, chance: 10},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 20, max_level: 20, chance: 10},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 17, max_level: 17, chance: 20},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 21, max_level: 21, chance: 10},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 31, max_level: 31, chance: 20},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 36, max_level: 36, chance: 15},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 41, max_level: 41, chance: 10},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 31, max_level: 31, chance: 20},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 41, max_level: 41, chance: 15},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 41, max_level: 41, chance: 15},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 46, max_level: 46, chance: 10},
    ],
    "Gloom": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 55, max_level: 55, chance: 10},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 58, max_level: 58, chance: 5},
        {location: "Road 12", method: "Walk", min_level: 29, max_level: 29, chance: 5},
        {location: "Road 13", method: "Walk", min_level: 29, max_level: 29, chance: 5},
        {location: "Road 14", method: "Walk", min_level: 30, max_level: 30, chance: 5},
        {location: "Road 15", method: "Walk", min_level: 30, max_level: 30, chance: 5},
    ],
    "Golbat": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 50, max_level: 50, chance: 20},
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 55, max_level: 55, chance: 20},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 52, max_level: 52, chance: 20},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 57, max_level: 57, chance: 20},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 54, max_level: 54, chance: 20},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 59, max_level: 59, chance: 20},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 27, max_level: 27, chance: 4},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 36, max_level: 36, chance: 1},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 36, max_level: 36, chance: 5},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 27, max_level: 27, chance: 20},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 27, max_level: 27, chance: 5},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 39, max_level: 39, chance: 10},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 44, max_level: 44, chance: 20},
    ],
    "Goldeen": [
        {location: "Celadon City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Celadon City", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Celadon City", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Celadon City", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Celadon City", method: "Super Rod", min_level: 20, max_level: 20, chance: 10},
        {location: "Cerulean Cave (1F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cerulean Cave (1F)", method: "Super Rod", min_level: 25, max_level: 25, chance: 40},
        {location: "Cerulean Cave (B1F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cerulean Cave (B1F)", method: "Super Rod", min_level: 30, max_level: 30, chance: 40},
        {location: "Cerulean City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cerulean City", method: "Super Rod", min_level: 25, max_level: 25, chance: 40},
        {location: "Cerulean City", method: "Super Rod", min_level: 30, max_level: 30, chance: 30},
        {location: "Cinnabar Island", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Fuchsia City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Pallet Town", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 10", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 11", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 12", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 13", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 17", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 18", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 19", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 20", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 21", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 22", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 23", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 24", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 24", method: "Super Rod", min_level: 20, max_level: 20, chance: 40},
        {location: "Road 24", method: "Super Rod", min_level: 25, max_level: 25, chance: 30},
        {location: "Road 24", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Road 25", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 6", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 6", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Road 6", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Road 6", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 6", method: "Super Rod", min_level: 20, max_level: 20, chance: 10},
        {location: "Safari Zone (Area 1, east)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (Area 2, north)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (Area 3, west)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (middle)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Seafoam Islands (B3F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Seafoam Islands (B4F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Vermilion City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Viridian City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
    ],
    "Golduck": [
        {location: "Road 6", method: "Surf", min_level: 15, max_level: 15, chance: 4},
        {location: "Road 6", method: "Surf", min_level: 20, max_level: 20, chance: 1},
    ],
    "Graveler": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 45, max_level: 45, chance: 15},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 50, max_level: 50, chance: 15},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 55, max_level: 55, chance: 15},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 41, max_level: 41, chance: 4},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 47, max_level: 47, chance: 1},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 44, max_level: 44, chance: 10},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 41, max_level: 41, chance: 10},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 47, max_level: 47, chance: 4},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 47, max_level: 47, chance: 1},
    ],
    "Grimer": [
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 23, max_level: 23, chance: 15},
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 26, max_level: 26, chance: 5},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 26, max_level: 26, chance: 15},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 29, max_level: 29, chance: 10},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 32, max_level: 32, chance: 5},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 35, max_level: 35, chance: 5},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 32, max_level: 32, chance: 15},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 35, max_level: 35, chance: 10},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 38, max_level: 38, chance: 5},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 35, max_level: 35, chance: 20},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 38, max_level: 38, chance: 20},
        {location: "Power Plant", method: "Walk", min_level: 33, max_level: 33, chance: 10},
        {location: "Power Plant", method: "Walk", min_level: 37, max_level: 37, chance: 5},
    ],
    "Growlithe": [
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 26, max_level: 26, chance: 10},
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 30, max_level: 30, chance: 5},
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 34, max_level: 34, chance: 4},
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 38, max_level: 38, chance: 1},
    ],
    "Gyarados": [
        {location: "Fuchsia City", method: "Super Rod", min_level: 15, max_level: 15, chance: 10},
    ],
    "Haunter": [
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 20, max_level: 20, chance: 4},
        {location: "Pokemon Tower (3F)", method: "Walk", min_level: 25, max_level: 25, chance: 1},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 20, max_level: 20, chance: 4},
        {location: "Pokemon Tower (4F)", method: "Walk", min_level: 25, max_level: 25, chance: 1},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 22, max_level: 22, chance: 4},
        {location: "Pokemon Tower (5F)", method: "Walk", min_level: 27, max_level: 27, chance: 1},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 22, max_level: 22, chance: 4},
        {location: "Pokemon Tower (6F)", method: "Walk", min_level: 27, max_level: 27, chance: 1},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 24, max_level: 24, chance: 4},
        {location: "Pokemon Tower (7F)", method: "Walk", min_level: 29, max_level: 29, chance: 1},
    ],
    "Hitmonchan": [
        {location: "Fighting Dojo", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ],
    "Hitmonlee": [
        {location: "Fighting Dojo", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ],
    "Horsea": [
        {location: "Road 10", method: "Super Rod", min_level: 10, max_level: 10, chance: 20},
        {location: "Road 11", method: "Super Rod", min_level: 5, max_level: 5, chance: 10},
        {location: "Road 12", method: "Super Rod", min_level: 20, max_level: 20, chance: 40},
        {location: "Road 12", method: "Super Rod", min_level: 25, max_level: 25, chance: 30},
        {location: "Road 13", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Road 13", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Vermilion City", method: "Super Rod", min_level: 5, max_level: 5, chance: 10},
    ],
    "Jigglypuff": [
        {location: "Road 5", method: "Walk", min_level: 3, max_level: 3, chance: 5},
        {location: "Road 5", method: "Walk", min_level: 5, max_level: 5, chance: 4},
        {location: "Road 5", method: "Walk", min_level: 7, max_level: 7, chance: 1},
        {location: "Road 6", method: "Walk", min_level: 3, max_level: 3, chance: 5},
        {location: "Road 6", method: "Walk", min_level: 5, max_level: 5, chance: 4},
        {location: "Road 6", method: "Walk", min_level: 7, max_level: 7, chance: 1},
        {location: "Road 7", method: "Walk", min_level: 19, max_level: 19, chance: 5},
        {location: "Road 7", method: "Walk", min_level: 24, max_level: 24, chance: 4},
        {location: "Road 7", method: "Walk", min_level: 24, max_level: 24, chance: 1},
        {location: "Road 8", method: "Walk", min_level: 19, max_level: 19, chance: 5},
        {location: "Road 8", method: "Walk", min_level: 24, max_level: 24, chance: 5},
    ],
    "Kabuto": [
        {location: "Cinnabar Lab (Cinnabar Island)", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ],
    "Kadabra": [
        {location: "Road 8", method: "Walk", min_level: 20, max_level: 20, chance: 4},
        {location: "Road 8", method: "Walk", min_level: 27, max_level: 27, chance: 1},
    ],
    "Kangaskhan": [
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 33, max_level: 33, chance: 5},
    ],
    "Kingler": [
        {location: "Road 10", method: "Super Rod", min_level: 25, max_level: 25, chance: 10},
        {location: "Road 25", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 25", method: "Super Rod", min_level: 25, max_level: 25, chance: 10},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 28, max_level: 28, chance: 5},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Seafoam Islands (B3F)", method: "Super Rod", min_level: 35, max_level: 35, chance: 20},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 30, max_level: 30, chance: 10},
        {location: "Seafoam Islands (B4F)", method: "Super Rod", min_level: 35, max_level: 35, chance: 20},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 32, max_level: 32, chance: 10},
    ],
    "Krabby": [
        {location: "Road 10", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Road 10", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Road 25", method: "Super Rod", min_level: 10, max_level: 10, chance: 40},
        {location: "Road 25", method: "Super Rod", min_level: 15, max_level: 15, chance: 30},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 25, max_level: 25, chance: 20},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 27, max_level: 27, chance: 15},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 27, max_level: 27, chance: 20},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 29, max_level: 29, chance: 5},
        {location: "Seafoam Islands (B3F)", method: "Super Rod", min_level: 25, max_level: 25, chance: 40},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 29, max_level: 29, chance: 15},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 31, max_level: 31, chance: 5},
        {location: "Seafoam Islands (B4F)", method: "Super Rod", min_level: 25, max_level: 25, chance: 40},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 30, max_level: 30, chance: 15},
    ],
    "Lapras": [
        {location: "Silph Co. 7F", method: "Gift", min_level: 15, max_level: 15, chance: 100},
    ],
    "Lickitung": [
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 55, max_level: 55, chance: 4},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 50, max_level: 50, chance: 1},
    ],
    "Machoke": [
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 39, max_level: 39, chance: 4},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 42, max_level: 42, chance: 1},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 42, max_level: 42, chance: 5},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 45, max_level: 45, chance: 5},
    ],
    "Machop": [
        {location: "Road 10", method: "Walk", min_level: 16, max_level: 16, chance: 4},
        {location: "Road 10", method: "Walk", min_level: 18, max_level: 18, chance: 1},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 17, max_level: 17, chance: 5},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 19, max_level: 19, chance: 4},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 21, max_level: 21, chance: 1},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 18, max_level: 18, chance: 15},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 20, max_level: 20, chance: 5},
    ],
    "Magikarp": [
        {location: "Celadon City", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Cerulean Cave (1F)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Cerulean Cave (B1F)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Cerulean City", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Cinnabar Island", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Fuchsia City", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Fuchsia City", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Fuchsia City", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Fuchsia City", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Pallet Town", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Pokemon Center (Road 3)", method: "Gift", min_level: 5, max_level: 5, chance: 100},
        {location: "Pokemon Center (Road 4)", method: "Gift", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 10", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 11", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 12", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 13", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 17", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 18", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 19", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 20", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 21", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 22", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 23", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 24", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 25", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Road 6", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Safari Zone (Area 1, east)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Safari Zone (Area 1, east)", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Safari Zone (Area 1, east)", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Safari Zone (Area 1, east)", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Safari Zone (Area 2, north)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Safari Zone (Area 2, north)", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Safari Zone (Area 2, north)", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Safari Zone (Area 2, north)", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Safari Zone (Area 3, west)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Safari Zone (Area 3, west)", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Safari Zone (Area 3, west)", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Safari Zone (Area 3, west)", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Safari Zone (middle)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Safari Zone (middle)", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Safari Zone (middle)", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Seafoam Islands (B3F)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Seafoam Islands (B4F)", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Vermilion City", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
        {location: "Viridian City", method: "Old Rod", min_level: 5, max_level: 5, chance: 100},
    ],
    "Magnemite": [
        {location: "Power Plant", method: "Walk", min_level: 30, max_level: 30, chance: 20},
        {location: "Power Plant", method: "Walk", min_level: 35, max_level: 35, chance: 20},
        {location: "Road 10", method: "Walk", min_level: 16, max_level: 16, chance: 20},
        {location: "Road 10", method: "Walk", min_level: 18, max_level: 18, chance: 15},
        {location: "Road 10", method: "Walk", min_level: 20, max_level: 20, chance: 10},
        {location: "Road 10", method: "Walk", min_level: 22, max_level: 22, chance: 5},
    ],
    "Magneton": [
        {location: "Power Plant", method: "Walk", min_level: 33, max_level: 33, chance: 15},
        {location: "Power Plant", method: "Walk", min_level: 38, max_level: 38, chance: 5},
    ],
    "Mankey": [
        {location: "Road 22", method: "Walk", min_level: 3, max_level: 3, chance: 15},
        {location: "Road 22", method: "Walk", min_level: 5, max_level: 5, chance: 5},
        {location: "Road 23", method: "Walk", min_level: 36, max_level: 36, chance: 15},
        {location: "Road 23", method: "Walk", min_level: 41, max_level: 41, chance: 5},
        {location: "Road 3", method: "Walk", min_level: 9, max_level: 9, chance: 15},
        {location: "Road 4", method: "Walk", min_level: 9, max_level: 9, chance: 15},
    ],
    "Marowak": [
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 24, max_level: 24, chance: 5},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 24, max_level: 24, chance: 5},
    ],
    "Metapod": [
        {location: "Viridian Forest", method: "Walk", min_level: 4, max_level: 4, chance: 20},
        {location: "Viridian Forest", method: "Walk", min_level: 6, max_level: 6, chance: 5},
    ],
    "Mewtwo": [
        {location: "Cerulean Cave (B1F)", method: "Static", min_level: 70, max_level: 70, chance: 100},
    ],
    "Moltres": [
        {location: "Victory Road 2 (2F)", method: "Static", min_level: 50, max_level: 50, chance: 100},
    ],
    "Muk": [
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 35, max_level: 35, chance: 4},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 38, max_level: 38, chance: 1},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 38, max_level: 38, chance: 4},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 41, max_level: 41, chance: 1},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 41, max_level: 41, chance: 10},
        {location: "Power Plant", method: "Walk", min_level: 33, max_level: 33, chance: 4},
        {location: "Power Plant", method: "Walk", min_level: 37, max_level: 37, chance: 1},
    ],
    "Nidoran F": [
        {location: "Road 10", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 4, max_level: 4, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 6, max_level: 6, chance: 5},
        {location: "Road 22", method: "Walk", min_level: 2, max_level: 2, chance: 20},
        {location: "Road 22", method: "Walk", min_level: 4, max_level: 4, chance: 10},
        {location: "Road 9", method: "Walk", min_level: 16, max_level: 16, chance: 20},
        {location: "Road 9", method: "Walk", min_level: 18, max_level: 18, chance: 10},
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 29, max_level: 29, chance: 20},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 14, max_level: 14, chance: 20},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 21, max_level: 21, chance: 20},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
    ],
    "Nidoran M": [
        {location: "Road 10", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 4, max_level: 4, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 6, max_level: 6, chance: 5},
        {location: "Road 22", method: "Walk", min_level: 2, max_level: 2, chance: 20},
        {location: "Road 22", method: "Walk", min_level: 4, max_level: 4, chance: 10},
        {location: "Road 9", method: "Walk", min_level: 16, max_level: 16, chance: 20},
        {location: "Road 9", method: "Walk", min_level: 18, max_level: 18, chance: 10},
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 21, max_level: 21, chance: 20},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 29, max_level: 29, chance: 20},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 14, max_level: 14, chance: 20},
    ],
    "Nidorina": [
        {location: "Road 23", method: "Walk", min_level: 41, max_level: 41, chance: 20},
        {location: "Road 23", method: "Walk", min_level: 44, max_level: 44, chance: 10},
        {location: "Road 9", method: "Walk", min_level: 18, max_level: 18, chance: 5},
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 32, max_level: 32, chance: 10},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 23, max_level: 23, chance: 10},
    ],
    "Nidorino": [
        {location: "Road 23", method: "Walk", min_level: 41, max_level: 41, chance: 20},
        {location: "Road 23", method: "Walk", min_level: 44, max_level: 44, chance: 10},
        {location: "Road 9", method: "Walk", min_level: 18, max_level: 18, chance: 5},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 32, max_level: 32, chance: 10},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 23, max_level: 23, chance: 10},
    ],
    "Oddish": [
        {location: "Road 12", method: "Walk", min_level: 25, max_level: 25, chance: 20},
        {location: "Road 12", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Road 13", method: "Walk", min_level: 25, max_level: 25, chance: 20},
        {location: "Road 13", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Road 14", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Road 14", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 15", method: "Walk", min_level: 26, max_level: 26, chance: 20},
        {location: "Road 15", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 24", method: "Walk", min_level: 12, max_level: 12, chance: 20},
        {location: "Road 24", method: "Walk", min_level: 14, max_level: 14, chance: 10},
        {location: "Road 25", method: "Walk", min_level: 12, max_level: 12, chance: 20},
        {location: "Road 25", method: "Walk", min_level: 14, max_level: 14, chance: 10},
    ],
    "Omanyte": [
        {location: "Cinnabar Lab (Cinnabar Island)", method: "Gift", min_level: 30, max_level: 30, chance: 100},
    ],
    "Onix": [
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 14, max_level: 14, chance: 5},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 18, max_level: 18, chance: 4},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 22, max_level: 22, chance: 1},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 43, max_level: 43, chance: 5},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 45, max_level: 45, chance: 5},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 45, max_level: 45, chance: 5},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 47, max_level: 47, chance: 5},
        {location: "Victory Road 2 (3F)", method: "Walk", min_level: 49, max_level: 49, chance: 10},
    ],
    "Paras": [
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 9, max_level: 9, chance: 5},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 11, max_level: 11, chance: 5},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 13, max_level: 13, chance: 15},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 27, max_level: 27, chance: 5},
    ],
    "Parasect": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 54, max_level: 54, chance: 5},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 32, max_level: 32, chance: 5},
    ],
    "Pidgeotto": [
        {location: "Road 11", method: "Walk", min_level: 18, max_level: 18, chance: 5},
        {location: "Road 11", method: "Walk", min_level: 20, max_level: 20, chance: 5},
        {location: "Road 12", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 13", method: "Walk", min_level: 28, max_level: 28, chance: 15},
        {location: "Road 14", method: "Walk", min_level: 30, max_level: 30, chance: 10},
        {location: "Road 15", method: "Walk", min_level: 32, max_level: 32, chance: 10},
        {location: "Road 21", method: "Walk", min_level: 17, max_level: 17, chance: 5},
        {location: "Road 21", method: "Walk", min_level: 19, max_level: 19, chance: 4},
        {location: "Road 21", method: "Walk", min_level: 15, max_level: 15, chance: 1},
        {location: "Road 24", method: "Walk", min_level: 17, max_level: 17, chance: 1},
        {location: "Road 25", method: "Walk", min_level: 17, max_level: 17, chance: 1},
        {location: "Road 5", method: "Walk", min_level: 17, max_level: 17, chance: 5},
        {location: "Road 6", method: "Walk", min_level: 17, max_level: 17, chance: 5},
        {location: "Road 7", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Road 8", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Viridian Forest", method: "Walk", min_level: 9, max_level: 9, chance: 1},
    ],
    "Pidgey": [
        {location: "Road 1", method: "Walk", min_level: 3, max_level: 3, chance: 20},
        {location: "Road 1", method: "Walk", min_level: 4, max_level: 4, chance: 20},
        {location: "Road 1", method: "Walk", min_level: 2, max_level: 2, chance: 10},
        {location: "Road 1", method: "Walk", min_level: 3, max_level: 3, chance: 10},
        {location: "Road 1", method: "Walk", min_level: 5, max_level: 5, chance: 5},
        {location: "Road 1", method: "Walk", min_level: 6, max_level: 6, chance: 4},
        {location: "Road 1", method: "Walk", min_level: 7, max_level: 7, chance: 1},
        {location: "Road 11", method: "Walk", min_level: 16, max_level: 16, chance: 20},
        {location: "Road 11", method: "Walk", min_level: 18, max_level: 18, chance: 15},
        {location: "Road 12", method: "Walk", min_level: 28, max_level: 28, chance: 15},
        {location: "Road 13", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 3, max_level: 3, chance: 20},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 5, max_level: 5, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 7, max_level: 7, chance: 4},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 7, max_level: 7, chance: 1},
        {location: "Road 21", method: "Walk", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 21", method: "Walk", min_level: 13, max_level: 13, chance: 15},
        {location: "Road 21", method: "Walk", min_level: 11, max_level: 11, chance: 10},
        {location: "Road 21", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 24", method: "Walk", min_level: 13, max_level: 13, chance: 15},
        {location: "Road 24", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 24", method: "Walk", min_level: 17, max_level: 17, chance: 4},
        {location: "Road 25", method: "Walk", min_level: 13, max_level: 13, chance: 15},
        {location: "Road 25", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 25", method: "Walk", min_level: 17, max_level: 17, chance: 4},
        {location: "Road 5", method: "Walk", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 5", method: "Walk", min_level: 16, max_level: 16, chance: 10},
        {location: "Road 5", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 6", method: "Walk", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 6", method: "Walk", min_level: 16, max_level: 16, chance: 10},
        {location: "Road 6", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 7", method: "Walk", min_level: 20, max_level: 20, chance: 20},
        {location: "Road 7", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Road 8", method: "Walk", min_level: 20, max_level: 20, chance: 20},
        {location: "Road 8", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Viridian Forest", method: "Walk", min_level: 4, max_level: 4, chance: 10},
        {location: "Viridian Forest", method: "Walk", min_level: 6, max_level: 6, chance: 10},
        {location: "Viridian Forest", method: "Walk", min_level: 8, max_level: 8, chance: 4},
    ],
    "Pikachu": [
        {location: "Pallet Town", method: "Gift", min_level: 5, max_level: 5, chance: 100},
    ],
    "Pinsir": [
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 15, max_level: 15, chance: 1},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 25, max_level: 25, chance: 4},
    ],
    "Poliwag": [
        {location: "Celadon City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cerulean Cave (1F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cerulean Cave (B1F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cerulean City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Cinnabar Island", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Fuchsia City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Pallet Town", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 10", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 11", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 12", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 13", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 17", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 18", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 19", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 20", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 21", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 22", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 22", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Road 22", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Road 22", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 23", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 23", method: "Super Rod", min_level: 25, max_level: 25, chance: 40},
        {location: "Road 23", method: "Super Rod", min_level: 30, max_level: 30, chance: 30},
        {location: "Road 24", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 25", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Road 6", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (Area 1, east)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (Area 2, north)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (Area 3, west)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Safari Zone (middle)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Seafoam Islands (B3F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Seafoam Islands (B4F)", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Vermilion City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Viridian City", method: "Good Rod", min_level: 10, max_level: 10, chance: 50},
        {location: "Viridian City", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Viridian City", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Viridian City", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Viridian City", method: "Super Rod", min_level: 10, max_level: 10, chance: 10},
    ],
    "Poliwhirl": [
        {location: "Road 22", method: "Super Rod", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 23", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Road 23", method: "Super Rod", min_level: 40, max_level: 40, chance: 10},
    ],
    "Ponyta": [
        {location: "Road 17", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Road 17", method: "Walk", min_level: 30, max_level: 30, chance: 10},
        {location: "Road 17", method: "Walk", min_level: 32, max_level: 32, chance: 4},
    ],
    "Primeape": [
        {location: "Road 23", method: "Walk", min_level: 41, max_level: 41, chance: 4},
        {location: "Road 23", method: "Walk", min_level: 46, max_level: 46, chance: 1},
    ],
    "Psyduck": [
        {location: "Road 6", method: "Surf", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 6", method: "Surf", min_level: 15, max_level: 15, chance: 15},
        {location: "Road 6", method: "Surf", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 6", method: "Surf", min_level: 15, max_level: 15, chance: 5},
    ],
    "Raticate": [
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 34, max_level: 34, chance: 20},
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 37, max_level: 37, chance: 10},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 37, max_level: 37, chance: 20},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 40, max_level: 40, chance: 10},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 40, max_level: 40, chance: 20},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 43, max_level: 43, chance: 10},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 37, max_level: 37, chance: 15},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 40, max_level: 40, chance: 10},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 43, max_level: 43, chance: 10},
        {location: "Pokemon Mansion (B1F)", method: "Walk", min_level: 46, max_level: 46, chance: 5},
        {location: "Road 10", method: "Walk", min_level: 20, max_level: 20, chance: 5},
        {location: "Road 11", method: "Walk", min_level: 17, max_level: 17, chance: 1},
        {location: "Road 16", method: "Walk", min_level: 25, max_level: 25, chance: 4},
        {location: "Road 16", method: "Walk", min_level: 26, max_level: 26, chance: 1},
        {location: "Road 18", method: "Walk", min_level: 25, max_level: 25, chance: 4},
        {location: "Road 18", method: "Walk", min_level: 26, max_level: 26, chance: 1},
        {location: "Road 21", method: "Walk", min_level: 15, max_level: 15, chance: 5},
        {location: "Road 9", method: "Walk", min_level: 20, max_level: 20, chance: 4},
    ],
    "Rattata": [
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 34, max_level: 34, chance: 20},
        {location: "Pokemon Mansion (1F)", method: "Walk", min_level: 37, max_level: 37, chance: 10},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 37, max_level: 37, chance: 20},
        {location: "Pokemon Mansion (2F)", method: "Walk", min_level: 40, max_level: 40, chance: 10},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 40, max_level: 40, chance: 20},
        {location: "Pokemon Mansion (3F)", method: "Walk", min_level: 43, max_level: 43, chance: 10},
        {location: "Road 1", method: "Walk", min_level: 2, max_level: 2, chance: 15},
        {location: "Road 1", method: "Walk", min_level: 3, max_level: 3, chance: 10},
        {location: "Road 1", method: "Walk", min_level: 4, max_level: 4, chance: 5},
        {location: "Road 10", method: "Walk", min_level: 18, max_level: 18, chance: 20},
        {location: "Road 11", method: "Walk", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 11", method: "Walk", min_level: 17, max_level: 17, chance: 10},
        {location: "Road 16", method: "Walk", min_level: 23, max_level: 23, chance: 15},
        {location: "Road 16", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Road 18", method: "Walk", min_level: 23, max_level: 23, chance: 15},
        {location: "Road 18", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 3, max_level: 3, chance: 20},
        {location: "Road 2 (south, towards Viridian City)", method: "Walk", min_level: 4, max_level: 4, chance: 15},
        {location: "Road 21", method: "Walk", min_level: 13, max_level: 13, chance: 20},
        {location: "Road 21", method: "Walk", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 22", method: "Walk", min_level: 3, max_level: 3, chance: 10},
        {location: "Road 3", method: "Walk", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 3", method: "Walk", min_level: 12, max_level: 12, chance: 5},
        {location: "Road 4", method: "Walk", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 4", method: "Walk", min_level: 12, max_level: 12, chance: 5},
        {location: "Road 5", method: "Walk", min_level: 14, max_level: 14, chance: 20},
        {location: "Road 5", method: "Walk", min_level: 16, max_level: 16, chance: 10},
        {location: "Road 6", method: "Walk", min_level: 14, max_level: 14, chance: 20},
        {location: "Road 6", method: "Walk", min_level: 16, max_level: 16, chance: 10},
        {location: "Road 7", method: "Walk", min_level: 20, max_level: 20, chance: 15},
        {location: "Road 8", method: "Walk", min_level: 20, max_level: 20, chance: 15},
        {location: "Road 9", method: "Walk", min_level: 18, max_level: 18, chance: 15},
    ],
    "Rhydon": [
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 60, max_level: 60, chance: 4},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 58, max_level: 58, chance: 1},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 62, max_level: 62, chance: 10},
    ],
    "Rhyhorn": [
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 50, max_level: 50, chance: 10},
        {location: "Cerulean Cave (B1F)", method: "Walk", min_level: 52, max_level: 52, chance: 10},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 25, max_level: 25, chance: 10},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 20, max_level: 20, chance: 10},
    ],
    "Sandshrew": [
        {location: "Mount Moon (1F)", method: "Walk", min_level: 12, max_level: 12, chance: 4},
        {location: "Road 3", method: "Walk", min_level: 8, max_level: 8, chance: 10},
        {location: "Road 3", method: "Walk", min_level: 10, max_level: 10, chance: 5},
        {location: "Road 4", method: "Walk", min_level: 8, max_level: 8, chance: 10},
        {location: "Road 4", method: "Walk", min_level: 10, max_level: 10, chance: 5},
    ],
    "Sandslash": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 52, max_level: 52, chance: 10},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 56, max_level: 56, chance: 10},
    ],
    "Scyther": [
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 15, max_level: 15, chance: 1},
        {location: "Safari Zone (Area 2, north)", method: "Walk", min_level: 25, max_level: 25, chance: 4},
    ],
    "Seadra": [
        {location: "Road 12", method: "Super Rod", min_level: 25, max_level: 25, chance: 20},
        {location: "Road 12", method: "Super Rod", min_level: 35, max_level: 35, chance: 10},
        {location: "Road 13", method: "Super Rod", min_level: 20, max_level: 20, chance: 10},
    ],
    "Seaking": [
        {location: "Cerulean Cave (1F)", method: "Super Rod", min_level: 35, max_level: 35, chance: 30},
        {location: "Cerulean Cave (1F)", method: "Super Rod", min_level: 45, max_level: 45, chance: 20},
        {location: "Cerulean Cave (1F)", method: "Super Rod", min_level: 55, max_level: 55, chance: 10},
        {location: "Cerulean Cave (B1F)", method: "Super Rod", min_level: 40, max_level: 40, chance: 30},
        {location: "Cerulean Cave (B1F)", method: "Super Rod", min_level: 50, max_level: 50, chance: 20},
        {location: "Cerulean Cave (B1F)", method: "Super Rod", min_level: 60, max_level: 60, chance: 10},
        {location: "Cerulean City", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Cerulean City", method: "Super Rod", min_level: 40, max_level: 40, chance: 10},
        {location: "Road 24", method: "Super Rod", min_level: 30, max_level: 30, chance: 10},
    ],
    "Seel": [
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 22, max_level: 22, chance: 4},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 26, max_level: 26, chance: 1},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 24, max_level: 24, chance: 10},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 26, max_level: 26, chance: 10},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 30, max_level: 30, chance: 5},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 32, max_level: 32, chance: 10},
    ],
    "Shellder": [
        {location: "Road 17", method: "Super Rod", min_level: 25, max_level: 25, chance: 20},
        {location: "Road 17", method: "Super Rod", min_level: 35, max_level: 35, chance: 10},
        {location: "Road 18", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Road 18", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Road 18", method: "Super Rod", min_level: 40, max_level: 40, chance: 10},
        {location: "S.S. Anne dock", method: "Super Rod", min_level: 10, max_level: 10, chance: 10},
    ],
    "Slowbro": [
        {location: "Road 12", method: "Surf", min_level: 15, max_level: 15, chance: 4},
        {location: "Road 12", method: "Surf", min_level: 20, max_level: 20, chance: 1},
        {location: "Road 13", method: "Surf", min_level: 15, max_level: 15, chance: 4},
        {location: "Road 13", method: "Surf", min_level: 20, max_level: 20, chance: 1},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 31, max_level: 31, chance: 1},
    ],
    "Slowpoke": [
        {location: "Road 12", method: "Surf", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 12", method: "Surf", min_level: 15, max_level: 15, chance: 15},
        {location: "Road 12", method: "Surf", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 12", method: "Surf", min_level: 15, max_level: 15, chance: 5},
        {location: "Road 13", method: "Surf", min_level: 15, max_level: 15, chance: 20},
        {location: "Road 13", method: "Surf", min_level: 15, max_level: 15, chance: 15},
        {location: "Road 13", method: "Surf", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 13", method: "Surf", min_level: 15, max_level: 15, chance: 5},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 28, max_level: 28, chance: 10},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 30, max_level: 30, chance: 5},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 29, max_level: 29, chance: 10},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 31, max_level: 31, chance: 4},
    ],
    "Snorlax": [
        {location: "Road 12", method: "Pokeflute", min_level: 30, max_level: 30, chance: 100},
        {location: "Road 16", method: "Pokeflute", min_level: 30, max_level: 30, chance: 100},
    ],
    "Spearow": [
        {location: "Road 16", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Road 16", method: "Walk", min_level: 23, max_level: 23, chance: 5},
        {location: "Road 18", method: "Walk", min_level: 22, max_level: 22, chance: 20},
        {location: "Road 18", method: "Walk", min_level: 23, max_level: 23, chance: 5},
        {location: "Road 22", method: "Walk", min_level: 2, max_level: 2, chance: 5},
        {location: "Road 22", method: "Walk", min_level: 4, max_level: 4, chance: 4},
        {location: "Road 22", method: "Walk", min_level: 6, max_level: 6, chance: 1},
        {location: "Road 3", method: "Walk", min_level: 8, max_level: 8, chance: 20},
        {location: "Road 3", method: "Walk", min_level: 9, max_level: 9, chance: 20},
        {location: "Road 3", method: "Walk", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 3", method: "Walk", min_level: 11, max_level: 11, chance: 4},
        {location: "Road 3", method: "Walk", min_level: 12, max_level: 12, chance: 1},
        {location: "Road 4", method: "Walk", min_level: 8, max_level: 8, chance: 20},
        {location: "Road 4", method: "Walk", min_level: 9, max_level: 9, chance: 20},
        {location: "Road 4", method: "Walk", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 4", method: "Walk", min_level: 11, max_level: 11, chance: 4},
        {location: "Road 4", method: "Walk", min_level: 12, max_level: 12, chance: 1},
        {location: "Road 9", method: "Walk", min_level: 17, max_level: 17, chance: 10},
    ],
    "Squirtle": [
        {location: "Vermilion City", method: "Gift", min_level: 10, max_level: 10, chance: 100},
    ],
    "Staryu": [
        {location: "Cinnabar Island", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Cinnabar Island", method: "Super Rod", min_level: 10, max_level: 10, chance: 20},
        {location: "Pallet Town", method: "Super Rod", min_level: 10, max_level: 10, chance: 40},
        {location: "Pallet Town", method: "Super Rod", min_level: 5, max_level: 5, chance: 20},
        {location: "Road 19", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Road 20", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Road 21", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "S.S. Anne dock", method: "Super Rod", min_level: 15, max_level: 15, chance: 20},
        {location: "Seafoam Islands (B3F)", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Seafoam Islands (B3F)", method: "Super Rod", min_level: 40, max_level: 40, chance: 10},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 30, max_level: 30, chance: 10},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 30, max_level: 30, chance: 5},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 30, max_level: 30, chance: 4},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 30, max_level: 30, chance: 1},
        {location: "Seafoam Islands (B4F)", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Seafoam Islands (B4F)", method: "Super Rod", min_level: 40, max_level: 40, chance: 10},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 30, max_level: 30, chance: 10},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 30, max_level: 30, chance: 5},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 30, max_level: 30, chance: 4},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 30, max_level: 30, chance: 1},
    ],
    "Tangela": [
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 27, max_level: 27, chance: 1},
        {location: "Safari Zone (middle)", method: "Walk", min_level: 22, max_level: 22, chance: 4},
    ],
    "Tauros": [
        {location: "Safari Zone (Area 1, east)", method: "Walk", min_level: 21, max_level: 21, chance: 10},
        {location: "Safari Zone (Area 3, west)", method: "Walk", min_level: 21, max_level: 21, chance: 10},
    ],
    "Tentacool": [
        {location: "Cinnabar Island", method: "Super Rod", min_level: 15, max_level: 15, chance: 30},
        {location: "Cinnabar Island", method: "Super Rod", min_level: 30, max_level: 30, chance: 10},
        {location: "Pallet Town", method: "Super Rod", min_level: 10, max_level: 10, chance: 30},
        {location: "Pallet Town", method: "Super Rod", min_level: 20, max_level: 20, chance: 10},
        {location: "Road 11", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Road 11", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Road 11", method: "Super Rod", min_level: 10, max_level: 10, chance: 20},
        {location: "Road 13", method: "Super Rod", min_level: 10, max_level: 10, chance: 20},
        {location: "Road 17", method: "Super Rod", min_level: 5, max_level: 5, chance: 40},
        {location: "Road 17", method: "Super Rod", min_level: 15, max_level: 15, chance: 30},
        {location: "Road 18", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Road 19", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Road 19", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Road 19", method: "Surf", min_level: 5, max_level: 5, chance: 20},
        {location: "Road 19", method: "Surf", min_level: 10, max_level: 10, chance: 20},
        {location: "Road 19", method: "Surf", min_level: 15, max_level: 15, chance: 15},
        {location: "Road 19", method: "Surf", min_level: 5, max_level: 5, chance: 10},
        {location: "Road 19", method: "Surf", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 19", method: "Surf", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 19", method: "Surf", min_level: 20, max_level: 20, chance: 5},
        {location: "Road 19", method: "Surf", min_level: 30, max_level: 30, chance: 5},
        {location: "Road 19", method: "Surf", min_level: 35, max_level: 35, chance: 4},
        {location: "Road 19", method: "Surf", min_level: 40, max_level: 40, chance: 1},
        {location: "Road 20", method: "Super Rod", min_level: 20, max_level: 20, chance: 40},
        {location: "Road 20", method: "Surf", min_level: 5, max_level: 5, chance: 20},
        {location: "Road 20", method: "Surf", min_level: 10, max_level: 10, chance: 20},
        {location: "Road 20", method: "Surf", min_level: 15, max_level: 15, chance: 15},
        {location: "Road 20", method: "Surf", min_level: 5, max_level: 5, chance: 10},
        {location: "Road 20", method: "Surf", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 20", method: "Surf", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 20", method: "Surf", min_level: 20, max_level: 20, chance: 5},
        {location: "Road 20", method: "Surf", min_level: 30, max_level: 30, chance: 5},
        {location: "Road 20", method: "Surf", min_level: 35, max_level: 35, chance: 4},
        {location: "Road 20", method: "Surf", min_level: 40, max_level: 40, chance: 1},
        {location: "Road 21", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Road 21", method: "Super Rod", min_level: 30, max_level: 30, chance: 20},
        {location: "Road 21", method: "Surf", min_level: 5, max_level: 5, chance: 20},
        {location: "Road 21", method: "Surf", min_level: 10, max_level: 10, chance: 20},
        {location: "Road 21", method: "Surf", min_level: 15, max_level: 15, chance: 15},
        {location: "Road 21", method: "Surf", min_level: 5, max_level: 5, chance: 10},
        {location: "Road 21", method: "Surf", min_level: 10, max_level: 10, chance: 10},
        {location: "Road 21", method: "Surf", min_level: 15, max_level: 15, chance: 10},
        {location: "Road 21", method: "Surf", min_level: 20, max_level: 20, chance: 5},
        {location: "Road 21", method: "Surf", min_level: 30, max_level: 30, chance: 5},
        {location: "Road 21", method: "Surf", min_level: 35, max_level: 35, chance: 4},
        {location: "Road 21", method: "Surf", min_level: 40, max_level: 40, chance: 1},
        {location: "S.S. Anne dock", method: "Super Rod", min_level: 10, max_level: 10, chance: 40},
        {location: "S.S. Anne dock", method: "Super Rod", min_level: 15, max_level: 15, chance: 30},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 25, max_level: 25, chance: 20},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 30, max_level: 30, chance: 20},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 20, max_level: 20, chance: 15},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 35, max_level: 35, chance: 10},
        {location: "Seafoam Islands (B3F)", method: "Surf", min_level: 40, max_level: 40, chance: 5},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 25, max_level: 25, chance: 20},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 30, max_level: 30, chance: 20},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 20, max_level: 20, chance: 15},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 35, max_level: 35, chance: 10},
        {location: "Seafoam Islands (B4F)", method: "Surf", min_level: 40, max_level: 40, chance: 5},
        {location: "Vermilion City", method: "Super Rod", min_level: 15, max_level: 15, chance: 40},
        {location: "Vermilion City", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Vermilion City", method: "Super Rod", min_level: 10, max_level: 10, chance: 20},
    ],
    "Tentacruel": [
        {location: "Road 19", method: "Super Rod", min_level: 30, max_level: 30, chance: 10},
        {location: "Road 20", method: "Super Rod", min_level: 20, max_level: 20, chance: 30},
        {location: "Road 20", method: "Super Rod", min_level: 40, max_level: 40, chance: 10},
        {location: "Road 21", method: "Super Rod", min_level: 30, max_level: 30, chance: 10},
    ],
    "Venomoth": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 54, max_level: 54, chance: 5},
        {location: "Road 14", method: "Walk", min_level: 30, max_level: 30, chance: 1},
        {location: "Road 15", method: "Walk", min_level: 30, max_level: 30, chance: 1},
    ],
    "Venonat": [
        {location: "Road 14", method: "Walk", min_level: 24, max_level: 24, chance: 15},
        {location: "Road 14", method: "Walk", min_level: 27, max_level: 27, chance: 4},
        {location: "Road 15", method: "Walk", min_level: 24, max_level: 24, chance: 15},
        {location: "Road 15", method: "Walk", min_level: 27, max_level: 27, chance: 4},
        {location: "Road 24", method: "Walk", min_level: 13, max_level: 13, chance: 5},
        {location: "Road 24", method: "Walk", min_level: 16, max_level: 16, chance: 5},
        {location: "Road 25", method: "Walk", min_level: 13, max_level: 13, chance: 5},
        {location: "Road 25", method: "Walk", min_level: 16, max_level: 16, chance: 5},
    ],
    "Voltorb": [
        {location: "Power Plant", method: "Static", min_level: 40, max_level: 40, chance: 100},
        {location: "Power Plant", method: "Walk", min_level: 33, max_level: 33, chance: 10},
        {location: "Power Plant", method: "Walk", min_level: 37, max_level: 37, chance: 10},
    ],
    "Weepinbell": [
        {location: "Cerulean Cave (1F)", method: "Walk", min_level: 55, max_level: 55, chance: 10},
        {location: "Cerulean Cave (2F)", method: "Walk", min_level: 58, max_level: 58, chance: 5},
        {location: "Road 12", method: "Walk", min_level: 29, max_level: 29, chance: 5},
        {location: "Road 13", method: "Walk", min_level: 29, max_level: 29, chance: 5},
        {location: "Road 14", method: "Walk", min_level: 30, max_level: 30, chance: 5},
        {location: "Road 15", method: "Walk", min_level: 30, max_level: 30, chance: 5},
    ],
    "Zapdos": [
        {location: "Power Plant", method: "Static", min_level: 50, max_level: 50, chance: 100},
    ],
    "Zubat": [
        {location: "Mount Moon (1F)", method: "Walk", min_level: 8, max_level: 8, chance: 20},
        {location: "Mount Moon (1F)", method: "Walk", min_level: 9, max_level: 9, chance: 20},
        {location: "Mount Moon (1F)", method: "Walk", min_level: 6, max_level: 6, chance: 10},
        {location: "Mount Moon (1F)", method: "Walk", min_level: 7, max_level: 7, chance: 10},
        {location: "Mount Moon (1F)", method: "Walk", min_level: 10, max_level: 10, chance: 10},
        {location: "Mount Moon (1F)", method: "Walk", min_level: 11, max_level: 11, chance: 5},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 8, max_level: 8, chance: 20},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 9, max_level: 9, chance: 20},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 10, max_level: 10, chance: 15},
        {location: "Mount Moon (B1F)", method: "Walk", min_level: 11, max_level: 11, chance: 10},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 10, max_level: 10, chance: 20},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 11, max_level: 11, chance: 10},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 12, max_level: 12, chance: 10},
        {location: "Mount Moon (B2F)", method: "Walk", min_level: 13, max_level: 13, chance: 5},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 15, max_level: 15, chance: 20},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 17, max_level: 17, chance: 15},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 19, max_level: 19, chance: 10},
        {location: "Rock Tunnel (B1F)", method: "Walk", min_level: 21, max_level: 21, chance: 5},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 20, max_level: 20, chance: 20},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 21, max_level: 21, chance: 10},
        {location: "Rock Tunnel (B2F)", method: "Walk", min_level: 22, max_level: 22, chance: 10},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 18, max_level: 18, chance: 20},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 36, max_level: 36, chance: 10},
        {location: "Seafoam Islands (1F)", method: "Walk", min_level: 9, max_level: 9, chance: 5},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 27, max_level: 27, chance: 20},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 36, max_level: 36, chance: 15},
        {location: "Seafoam Islands (B1F)", method: "Walk", min_level: 18, max_level: 18, chance: 5},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 27, max_level: 27, chance: 20},
        {location: "Seafoam Islands (B2F)", method: "Walk", min_level: 36, max_level: 36, chance: 15},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
        {location: "Seafoam Islands (B3F)", method: "Walk", min_level: 27, max_level: 27, chance: 10},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 36, max_level: 36, chance: 20},
        {location: "Seafoam Islands (B4F)", method: "Walk", min_level: 45, max_level: 45, chance: 5},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 39, max_level: 39, chance: 10},
        {location: "Victory Road 2 (1F)", method: "Walk", min_level: 44, max_level: 44, chance: 10},
        {location: "Victory Road 2 (2F)", method: "Walk", min_level: 44, max_level: 44, chance: 10},
    ]
};
